# Generated by Django 5.2.14 on 2026-05-19 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=255, unique=True, verbose_name='密钥哈希')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('permissions', models.JSONField(default=dict, verbose_name='权限')),
                ('ip_whitelist', models.JSONField(default=list, verbose_name='IP白名单')),
                ('call_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'db_table': 'accounts_apikey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255, verbose_name='游戏名称')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('encrypted_password', models.BinaryField(verbose_name='加密密码')),
                ('server', models.CharField(blank=True, max_length=255, verbose_name='服务器')),
                ('login_method', models.CharField(blank=True, max_length=100, verbose_name='登录方式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏账号',
                'verbose_name_plural': '游戏账号',
                'db_table': 'accounts_gameaccount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='操作')),
                ('resource_type', models.CharField(max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='资源ID')),
                ('details', models.JSONField(default=dict, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'accounts_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'resource_type'], name='idx_auditlog_action_res')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='登录位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'db_table': 'accounts_loginhistory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_loginhist_user_created')],
            },
        ),
    ]
