# Generated by Django 5.2.14 on 2026-05-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_oauth_totp'),
        ('resources', '0003_recognizerbenchmark_template_templateannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='default_resource_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_accounts', to='resources.resourcepack', verbose_name='默认资源包'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后检测时间'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='server_region',
            field=models.CharField(blank=True, max_length=200, verbose_name='区服'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='status',
            field=models.CharField(default='unknown', max_length=20, verbose_name='账户状态'),
        ),
        migrations.CreateModel(
            name='GameAccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分组名称')),
                ('slug', models.SlugField(max_length=200, verbose_name='分组标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '账户分组',
                'verbose_name_plural': '账户分组',
                'db_table': 'accounts_gameaccount_group',
                'ordering': ['name'],
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.gameaccountgroup', verbose_name='所属分组'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='encrypted_password',
            field=models.TextField(verbose_name='加密密码'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='game_name',
            field=models.CharField(max_length=200, verbose_name='游戏名称'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='login_method',
            field=models.CharField(choices=[('password', '密码登录'), ('qr_scan', '扫码登录'), ('token', 'Token 登录'), ('steam', 'Steam 登录')], default='password', max_length=20, verbose_name='登录方式'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='username',
            field=models.CharField(max_length=200, verbose_name='游戏用户名'),
        ),
        migrations.RemoveField(
            model_name='gameaccount',
            name='server',
        ),
        migrations.RemoveField(
            model_name='gameaccount',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='gameaccount',
            unique_together={('owner', 'game_name', 'username')},
        ),
    ]
