# Generated by Django 5.2.14 on 2026-05-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phase4_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
