# Generated by Django 5.2.14 on 2026-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phase5_bindings'),
        ('resources', '0003_recognizerbenchmark_template_templateannotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameaccount',
            name='default_resource_pack',
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='allowed_resource_packs',
            field=models.ManyToManyField(blank=True, related_name='allowed_accounts', to='resources.resourcepack', verbose_name='允许使用的资源包'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
