# Generated by Django 5.2.14 on 2026-05-31 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_gameaccount_default_resource_pack_and_more'),
        ('resources', '0005_config_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='resource_pack',
            field=models.ForeignKey(blank=True, help_text='账户绑定的资源包，换服务器只改此字段', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_game_accounts', to='resources.resourcepack', verbose_name='当前资源包'),
        ),
    ]
