# Generated by Django 5.2.14 on 2026-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gameaccount_resource_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='execution_count',
            field=models.IntegerField(default=0, verbose_name='执行次数'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='last_execution_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='登录次数'),
        ),
    ]
