# Generated by Django 5.2.15 on 2026-06-21 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_account_stats_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_jti', models.CharField(help_text='关联 simplejwt OutstandingToken 的 jti claim', max_length=255, unique=True, verbose_name='Refresh Token JTI')),
                ('device_name', models.CharField(blank=True, help_text='从 User-Agent 解析，如 "Chrome 120 on Windows 10"', max_length=255, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('api', 'API'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='设备类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='登录位置')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('expires_at', models.DateTimeField(help_text='跟随 refresh token 过期时间', verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, help_text='踢下线后置 False', verbose_name='是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户会话',
                'verbose_name_plural': '用户会话',
                'db_table': 'accounts_usersession',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_usersess_user_created'), models.Index(fields=['refresh_token_jti'], name='idx_usersess_jti'), models.Index(fields=['is_active'], name='idx_usersess_active')],
            },
        ),
    ]
