# Generated by Django 5.2.15 on 2026-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_session'),
    ]

    operations = [
        # M5: add max_length=1024 to user_agent TextFields so overly long
        # User-Agent payloads are rejected at the serializer/form layer.
        # TextField keeps the TEXT column type; max_length only adds validation.
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(
                blank=True,
                max_length=1024,
                verbose_name='User-Agent',
                help_text='登录时的 User-Agent 字符串',
            ),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(
                blank=True,
                max_length=1024,
                verbose_name='User-Agent',
                help_text='会话登录时的 User-Agent 字符串',
            ),
        ),
    ]
