# Generated by Django 5.2.15 on 2026-07-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_m5_user_agent_max_length'),
        ('resources', '0006_td004_single_source_of_truth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='call_count',
            field=models.IntegerField(default=0, help_text='API 密钥累计调用次数', verbose_name='调用次数'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='API 密钥的过期时间', null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='ip_whitelist',
            field=models.JSONField(default=list, help_text='允许调用 API 的 IP 白名单', verbose_name='IP白名单'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='标记 API 密钥是否启用', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(help_text='API 密钥的哈希值', max_length=255, unique=True, verbose_name='密钥哈希'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(help_text='API 密钥的显示名称', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='permissions',
            field=models.JSONField(default=dict, help_text='API 密钥的权限配置', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(help_text='API 密钥所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='allowed_resource_packs',
            field=models.ManyToManyField(blank=True, help_text='账号允许使用的资源包集合', related_name='allowed_accounts', to='resources.resourcepack', verbose_name='允许使用的资源包'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='encrypted_password',
            field=models.TextField(help_text='AES-256-GCM 加密后的密码', verbose_name='加密密码'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='execution_count',
            field=models.IntegerField(default=0, help_text='账号累计被执行次数', verbose_name='执行次数'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='game_name',
            field=models.CharField(help_text='账号所属的游戏名称', max_length=200, verbose_name='游戏名称'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='group',
            field=models.ForeignKey(blank=True, help_text='账号所属的分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.gameaccountgroup', verbose_name='所属分组'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='标记账号是否处于启用状态', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='last_check_at',
            field=models.DateTimeField(blank=True, help_text='账号最近一次状态检测时间', null=True, verbose_name='最后检测时间'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='last_execution_time',
            field=models.DateTimeField(blank=True, help_text='账号最近一次被执行的时间', null=True, verbose_name='最后执行时间'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='last_login_at',
            field=models.DateTimeField(blank=True, help_text='账号最近一次登录游戏的时间', null=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='login_count',
            field=models.IntegerField(default=0, help_text='账号累计登录次数', verbose_name='登录次数'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='login_method',
            field=models.CharField(choices=[('password', '密码登录'), ('qr_scan', '扫码登录'), ('token', 'Token 登录'), ('steam', 'Steam 登录')], default='password', help_text='登录方式: password/qr_scan/token/steam', max_length=20, verbose_name='登录方式'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='owner',
            field=models.ForeignKey(help_text='账号所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='server_region',
            field=models.CharField(blank=True, help_text='账号所在的游戏区服', max_length=200, verbose_name='区服'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='status',
            field=models.CharField(default='unknown', help_text='游戏账号的当前状态', max_length=20, verbose_name='账户状态'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='username',
            field=models.CharField(help_text='游戏账号的用户名', max_length=200, verbose_name='游戏用户名'),
        ),
        migrations.AlterField(
            model_name='gameaccountgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='gameaccountgroup',
            name='name',
            field=models.CharField(help_text='分组的显示名称', max_length=200, verbose_name='分组名称'),
        ),
        migrations.AlterField(
            model_name='gameaccountgroup',
            name='owner',
            field=models.ForeignKey(help_text='分组所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='gameaccountgroup',
            name='slug',
            field=models.SlugField(help_text='分组的 URL 标识', max_length=200, verbose_name='分组标识'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='登录时的 IP 地址', verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='location',
            field=models.CharField(blank=True, help_text='IP 解析出的地理位置', max_length=255, verbose_name='登录位置'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(help_text='登录的用户', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='标记用户下次登录是否需修改密码', verbose_name='首次登录需修改密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('google', 'Google')], help_text='OAuth 登录的提供商', max_length=20, null=True, verbose_name='OAuth 提供商'),
        ),
        migrations.AlterField(
            model_name='user',
            name='oauth_uid',
            field=models.CharField(blank=True, help_text='OAuth 提供商返回的用户唯一 ID', max_length=255, null=True, verbose_name='OAuth 用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Operator'), ('admin', 'Admin')], default='viewer', help_text='角色: viewer/operator/admin', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='标记用户是否已启用 2FA', verbose_name='2FA 已启用'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP 2FA 的密钥', max_length=64, null=True, verbose_name='TOTP 密钥'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='会话创建(登录)的时间', verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('api', 'API'), ('unknown', 'Unknown')], default='unknown', help_text='设备类型: web/mobile/desktop/api/unknown', max_length=20, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='会话登录时的 IP 地址', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='用户最近一次活动的时间', verbose_name='最后活动时间'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, help_text='IP 解析出的地理位置', max_length=255, verbose_name='登录位置'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(help_text='会话所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
