# Generated by Django 5.2.15 on 2026-07-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auditlog'),
        ('gamestate', '0003_gameprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameaccount',
            name='allowed_resource_packs',
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='game_profile',
            field=models.ForeignKey(blank=True, help_text='Window-centric: 明确归属，替代 game_name 字符串弱关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_accounts', to='gamestate.gameprofile', verbose_name='所属游戏档案'),
        ),
    ]
