# Generated by Django 5.2.15 on 2026-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_window_centric_game_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='game_name',
            field=models.CharField(help_text='[Deprecated TD-259 #23] 优先用 game_profile FK; 此字段仅作历史兼容', max_length=200, verbose_name='游戏名称'),
        ),
    ]
