# Generated by Django 5.2.15 on 2026-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_gameaccount_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='encrypted_password',
            field=models.TextField(help_text='AES-256-GCM 加密后的密码', max_length=512, verbose_name='加密密码'),
        ),
    ]
