# Generated by Django 5.2.15 on 2026-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_td295_db_index_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, help_text='登录时的 IP 地址', verbose_name='IP地址'),
        ),
    ]
