# Generated by Django 5.2.15 on 2026-08-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_game_account_profile_retire'),
        ('gamestate', '0009_add_allowed_device_types_to_gameprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='game_profile',
            field=models.ForeignKey(help_text='Window-centric 唯一游戏维度 (spec 2026-08-29-game-account-game-name-retirement 后非空)', on_delete=django.db.models.deletion.PROTECT, related_name='game_accounts', to='gamestate.gameprofile', verbose_name='所属游戏档案'),
        ),
    ]
