# Generated by Django 5.2.15 on 2026-08-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_gameaccount_game_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameaccount',
            name='game_name',
        ),
    ]
