# Generated by Django 5.2.14 on 2026-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=64, unique=True, verbose_name='Agent 唯一标识')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('os_info', models.CharField(blank=True, max_length=255, verbose_name='操作系统信息')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('idle', 'Idle')], default='offline', max_length=20, verbose_name='状态')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('capabilities', models.JSONField(default=dict, verbose_name='能力标签')),
                ('agent_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='鉴权 Token')),
                ('is_local', models.BooleanField(default=False, verbose_name='是否本地 Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agent',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='idx_agent_status')],
            },
        ),
    ]
