# Generated by Django 5.2.14 on 2026-05-21 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_device_devicegroup_device_idx_device_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='adb_serial',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ADB 序列号'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_stats',
            field=models.JSONField(default=dict, verbose_name='设备性能统计'),
        ),
        migrations.AddField(
            model_name='device',
            name='emulator',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='模拟器类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='input_method',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='输入方式'),
        ),
        migrations.AddField(
            model_name='device',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='锁定时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_devices', to=settings.AUTH_USER_MODEL, verbose_name='锁定者'),
        ),
        migrations.AddField(
            model_name='device',
            name='screenshot_method',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='截图方式'),
        ),
        migrations.AddField(
            model_name='device',
            name='window_handle',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='窗口句柄'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='agents.devicegroup', verbose_name='父分组'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['locked_by'], name='idx_device_locked_by'),
        ),
    ]
