# Generated by Django 5.2.14 on 2026-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_add_agent_health_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='电池电量 (0-100)'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展元数据'),
        ),
        migrations.AddField(
            model_name='device',
            name='system_version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='系统版本'),
        ),
    ]
