# Generated by Django 5.2.15 on 2026-07-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_device_control_mode_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_token',
        ),
    ]
