# Generated by Django 5.2.15 on 2026-07-18 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_window_centric_game_account'),
        ('agents', '0016_remove_device_metadata'),
        ('gamestate', '0007_gameprofile_routine_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['game_profile'], name='idx_device_game_profile'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['game_account'], name='idx_device_game_account'),
        ),
    ]
