# Generated by Django 5.2.15 on 2026-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_device_game_profile_account_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active_channel',
            field=models.CharField(blank=True, help_text='spec 2026-08-29 P4: Channels channel_name 唯一连接指纹; 僵尸连接写入校验: heartbeat/offline 仅当 active_channel 匹配自身才生效', max_length=255, null=True, verbose_name='当前活跃 WS channel'),
        ),
    ]
