# Generated by Django 5.2.15 on 2026-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_agent_active_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='emulator',
            new_name='emulator_brand',
        ),
        migrations.AlterField(
            model_name='device',
            name='emulator_brand',
            field=models.CharField(blank=True, default='', help_text='模拟器品牌, 如 LDPlayer/Nox', max_length=32, verbose_name='模拟器品牌'),
        ),
    ]
