# Generated by Django 5.2.14 on 2026-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='技能名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('yaml_content', models.TextField(verbose_name='YAML 配置内容')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('applicable_scenarios', models.JSONField(default=list, verbose_name='适用场景')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Skill 定义',
                'verbose_name_plural': 'Skill 定义',
                'ordering': ['-id'],
            },
        ),
    ]
