# Generated by Django 5.2.14 on 2026-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skilldefinition_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldefinition',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
