# Generated by Django 5.2.15 on 2026-06-24 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skilldefinition_is_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('removed', '已下架')], default='pending', max_length=20, verbose_name='审核状态')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('rating_avg', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评分数量')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='版本号')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_skills', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_item', to='skills.skilldefinition', verbose_name='关联 Skill')),
            ],
            options={
                'verbose_name': 'Skill 市场条目',
                'verbose_name_plural': 'Skill 市场条目',
                'db_table': 'skills_marketitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillMarketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skills.skillmarketitem', verbose_name='市场条目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': 'Skill 市场评论',
                'verbose_name_plural': 'Skill 市场评论',
                'db_table': 'skills_marketreview',
                'ordering': ['-created_at'],
                'unique_together': {('item', 'user')},
            },
        ),
    ]
