# Generated by Django 5.2.14 on 2026-05-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worker',
            table='agents_agent',
        ),
    ]
