# Generated by Django 5.2.14 on 2026-05-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_agent_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('windows', 'Windows'), ('adb', 'ADB'), ('emulator', '模拟器')], max_length=20, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '忙碌'), ('error', '错误')], default='offline', max_length=20, verbose_name='状态')),
                ('resolution_width', models.IntegerField(blank=True, null=True, verbose_name='分辨率宽')),
                ('resolution_height', models.IntegerField(blank=True, null=True, verbose_name='分辨率高')),
                ('screenshot_fps', models.FloatField(default=0, verbose_name='截图帧率')),
                ('extra_info', models.JSONField(default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='workers.Worker', verbose_name='关联 Agent')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('devices', models.ManyToManyField(blank=True, related_name='groups', to='workers.Device', verbose_name='设备列表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '设备分组',
                'verbose_name_plural': '设备分组',
                'db_table': 'device_groups',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='idx_device_type'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='idx_device_status'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['agent'], name='idx_device_agent'),
        ),
    ]
