# Generated by Django 5.2.14 on 2026-05-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_device_adb_serial_device_device_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU 使用率 (%)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='memory_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='内存使用率 (%)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='screenshot_fps',
            field=models.FloatField(blank=True, null=True, verbose_name='截图帧率 (FPS)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('windows', 'Windows'), ('emulator', '模拟器')], max_length=20, verbose_name='设备类型'),
        ),
    ]
