# Generated by Django 5.2.15 on 2026-07-05 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_device_control_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='agent_id',
            field=models.CharField(help_text='Agent 注册时分配的唯一标识符', max_length=64, unique=True, verbose_name='Agent 唯一标识'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='capabilities',
            field=models.JSONField(default=dict, help_text='Agent 支持的能力标签字典', verbose_name='能力标签'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='cpu_usage',
            field=models.FloatField(blank=True, help_text='Agent 进程 CPU 占用百分比', null=True, verbose_name='CPU 使用率 (%)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hostname',
            field=models.CharField(help_text='Agent 所在主机的名称', max_length=255, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Agent 所在主机的 IP 地址', null=True, verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_local',
            field=models.BooleanField(default=False, help_text='标记是否为本地 Agent', verbose_name='是否本地 Agent'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='最近一次心跳上报时间', null=True, verbose_name='最后心跳时间'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='memory_usage',
            field=models.FloatField(blank=True, help_text='Agent 进程内存占用百分比', null=True, verbose_name='内存使用率 (%)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='os_info',
            field=models.CharField(blank=True, help_text='Agent 主机的操作系统描述', max_length=255, verbose_name='操作系统信息'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='screenshot_fps',
            field=models.FloatField(blank=True, help_text='Agent 支持的截图帧率', null=True, verbose_name='截图帧率 (FPS)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('idle', 'Idle')], default='offline', help_text='状态: online/offline/busy/idle', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='adb_serial',
            field=models.CharField(blank=True, default='', help_text='模拟器 ADB 设备序列号', max_length=255, verbose_name='ADB 序列号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='设备所属的 Agent 记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='workers.Worker', verbose_name='关联 Agent'),
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_level',
            field=models.IntegerField(blank=True, help_text='设备电池电量百分比', null=True, verbose_name='电池电量 (0-100)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_stats',
            field=models.JSONField(default=dict, help_text='设备性能统计数据', verbose_name='设备性能统计'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('windows', 'Windows'), ('emulator', '模拟器')], help_text='设备类型: windows/emulator', max_length=20, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='emulator',
            field=models.CharField(blank=True, default='', help_text='模拟器类型, 如 LDPlayer/Nox', max_length=32, verbose_name='模拟器类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='extra_info',
            field=models.JSONField(default=dict, help_text='设备的额外扩展信息', verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='设备最近一次心跳上报时间', null=True, verbose_name='最后心跳时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='设备被锁定的时间戳', null=True, verbose_name='锁定时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='当前锁定设备的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_devices', to=settings.AUTH_USER_MODEL, verbose_name='锁定者'),
        ),
        migrations.AlterField(
            model_name='device',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='设备的扩展元数据字典', verbose_name='扩展元数据'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='用户自定义的设备显示名称', max_length=255, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='resolution_height',
            field=models.IntegerField(blank=True, help_text='设备屏幕垂直像素数', null=True, verbose_name='分辨率高'),
        ),
        migrations.AlterField(
            model_name='device',
            name='resolution_width',
            field=models.IntegerField(blank=True, help_text='设备屏幕水平像素数', null=True, verbose_name='分辨率宽'),
        ),
        migrations.AlterField(
            model_name='device',
            name='screenshot_fps',
            field=models.FloatField(default=0, help_text='设备支持的截图帧率', verbose_name='截图帧率'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '忙碌'), ('error', '错误')], default='offline', help_text='状态: online/offline/busy/error', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='system_version',
            field=models.CharField(blank=True, default='', help_text='设备操作系统版本号', max_length=100, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='window_handle',
            field=models.CharField(blank=True, default='', help_text='Windows 窗口句柄标识', max_length=64, verbose_name='窗口句柄'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='分组包含的设备集合', related_name='groups', to='workers.Device', verbose_name='设备列表'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='name',
            field=models.CharField(help_text='设备分组的显示名称', max_length=255, verbose_name='分组名称'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父级分组, 用于构建树形结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workers.DeviceGroup', verbose_name='父分组'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='user',
            field=models.ForeignKey(help_text='分组所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('window_handle', ''), _negated=True), fields=('device_type', 'window_handle'), name='unique_device_type_window_handle'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('adb_serial', ''), _negated=True), fields=('device_type', 'adb_serial'), name='unique_device_type_adb_serial'),
        ),
    ]
