# Generated by Django 5.2.15 on 2026-07-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_r37_p0_device_unique_constraints'),
        ('tasks', '0025_pipeline_execution_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='game_profile',
            field=models.ForeignKey(blank=True, help_text='R37-P1: 设备所属的游戏档案（nullable，兼容未识别窗口）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='tasks.gameprofile', verbose_name='所属游戏档案'),
        ),
    ]
