# Generated by Django 5.2.15 on 2026-07-09 15:11

from django.db import migrations, models


def _derive_control_mode(screenshot_method: str, input_method: str) -> str:
    """Heuristic to map existing concrete methods to a control mode."""
    sm = (screenshot_method or '').lower()
    im = (input_method or '').lower()
    if im == 'postmessage':
        return 'background'
    if im == 'sendinput' and sm in ('printwindow', 'print', 'auto', ''):
        return 'pseudo_background'
    if im == 'sendinput':
        return 'foreground'
    return 'pseudo_background'


def forwards_derive_control_mode(apps, schema_editor):
    """Populate control_mode for existing rows based on their concrete methods."""
    Device = apps.get_model('workers', 'Device')
    for device in Device.objects.all():
        device.control_mode = _derive_control_mode(
            device.screenshot_method, device.input_method
        )
        device.save(update_fields=['control_mode'])


def reverse_noop(apps, schema_editor):
    """No-op reverse: the field will be removed by the reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_alter_device_game_profile_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='control_mode',
            field=models.CharField(choices=[('foreground', '前台'), ('background', '后台'), ('pseudo_background', '伪后台')], default='pseudo_background', help_text='设备控制模式：前台/后台/伪后台。伪后台会在点击时临时前台目标窗口并恢复', max_length=32, verbose_name='控制模式'),
        ),
        migrations.AlterField(
            model_name='device',
            name='input_method',
            field=models.CharField(blank=True, default='auto', help_text='设备使用的输入方式标识，"auto" 表示由平台 handler 自动选择；空值时由控制模式派生', max_length=64, verbose_name='输入方式'),
        ),
        migrations.AlterField(
            model_name='device',
            name='screenshot_method',
            field=models.CharField(blank=True, default='auto', help_text='设备使用的截图方式标识，"auto" 表示由平台 handler 自动选择；空值时由控制模式派生', max_length=64, verbose_name='截图方式'),
        ),
        migrations.RunPython(forwards_derive_control_mode, reverse_noop),
    ]
