# Generated by Django 5.2.15 on 2026-07-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_window_centric_game_account'),
        ('workers', '0012_add_device_control_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='game_account',
            field=models.ForeignKey(blank=True, help_text='Window-centric: 运行时绑定当前执行的账户，可随时切换（如换服、换号）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='accounts.gameaccount', verbose_name='运行时绑定账户'),
        ),
    ]
