# Generated by Django 5.2.15 on 2026-07-13 07:27

from django.db import migrations, models


def migrate_pseudo_background_to_auto(apps, schema_editor):
    """v3 §2.8.1: existing PSEUDO_BACKGROUND devices default to 'auto'
    so they inherit from GameProfile. Users who explicitly want
    pseudo_background can set it back via WindowManagementPage.
    """
    Device = apps.get_model('workers', 'Device')
    Device.objects.filter(control_mode='pseudo_background').update(control_mode='auto')


def restore_pseudo_background(apps, schema_editor):
    """Reverse migration: 'auto' back to pseudo_background (safe default)."""
    Device = apps.get_model('workers', 'Device')
    Device.objects.filter(control_mode='auto').update(control_mode='pseudo_background')


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_device_game_account_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='control_mode',
            field=models.CharField(choices=[('auto', '自动（继承）'), ('foreground', '前台'), ('background', '后台'), ('pseudo_background', '伪后台')], default='auto', help_text='设备控制模式：auto（继承 GameProfile）/前台/后台/伪后台。伪后台会在点击时临时前台目标窗口并恢复', max_length=32, verbose_name='控制模式'),
        ),
        migrations.RunPython(
            migrate_pseudo_background_to_auto,
            reverse_code=restore_pseudo_background,
        ),
    ]
