# Generated by Django 5.2.15 on 2026-07-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_remove_agent_agent_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='metadata',
        ),
    ]
