# Generated by Django 5.2.14 on 2026-05-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('rule_definition', models.JSONField(default=dict, verbose_name='规则定义')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_rules', to='resources.resourcepack', verbose_name='资源包')),
            ],
            options={
                'verbose_name': '监控规则',
                'verbose_name_plural': '监控规则',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MonitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='事件类型')),
                ('handling_result', models.CharField(blank=True, max_length=255, verbose_name='处理结果')),
                ('screenshot_path', models.CharField(blank=True, max_length=512, verbose_name='截图路径')),
                ('event_data', models.JSONField(blank=True, default=dict, verbose_name='事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_events', to='agents.agent', verbose_name='关联 Agent')),
                ('resource_pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_events', to='resources.resourcepack', verbose_name='资源包')),
            ],
            options={
                'verbose_name': '监控事件',
                'verbose_name_plural': '监控事件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='idx_monitorevent_agent_created')],
            },
        ),
    ]
