# Generated by Django 5.2.15 on 2026-07-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_r37_p1_game_profile_fk'),
        ('monitors', '0003_alert_escalation'),
        ('resources', '0008_templateeffectiveness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorevent',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='确认处理该事件的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='agent',
            field=models.ForeignKey(help_text='事件来源的 Agent 记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_events', to='workers.Worker', verbose_name='关联 Agent'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='event_data',
            field=models.JSONField(blank=True, default=dict, help_text='事件的详细数据', verbose_name='事件数据'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='event_type',
            field=models.CharField(help_text='监控事件的类型标识', max_length=100, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='handling_result',
            field=models.CharField(blank=True, help_text='事件处理结果的描述', max_length=255, verbose_name='处理结果'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='resource_pack',
            field=models.ForeignKey(help_text='关联的资源包记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_events', to='resources.resourcepack', verbose_name='资源包'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='screenshot_path',
            field=models.CharField(blank=True, help_text='事件触发时的截图文件路径', max_length=512, verbose_name='截图路径'),
        ),
        migrations.AlterField(
            model_name='monitorrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='monitorrule',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='标记规则是否处于启用状态', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='monitorrule',
            name='name',
            field=models.CharField(help_text='监控规则的显示名称', max_length=255, verbose_name='规则名称'),
        ),
        migrations.AlterField(
            model_name='monitorrule',
            name='resource_pack',
            field=models.ForeignKey(help_text='关联的资源包记录', on_delete=django.db.models.deletion.CASCADE, related_name='monitor_rules', to='resources.resourcepack', verbose_name='资源包'),
        ),
        migrations.AlterField(
            model_name='monitorrule',
            name='rule_definition',
            field=models.JSONField(default=dict, help_text='监控规则的完整定义 JSON', verbose_name='规则定义'),
        ),
        migrations.AlterField(
            model_name='monitorrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
    ]
