# Generated by Django 5.2.15 on 2026-08-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_device_game_profile_account_indexes'),
        ('monitors', '0004_alter_monitorevent_acknowledged_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('value', models.FloatField(verbose_name='指标值')),
                ('labels', models.JSONField(blank=True, default=dict, verbose_name='标签')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间戳')),
                ('agent', models.ForeignKey(blank=True, help_text='Agent that reported this metric (null for system-level metrics).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='workers.Worker', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'SLA 指标',
                'verbose_name_plural': 'SLA 指标',
                'db_table': 'monitors_slametric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='idx_monitors_slametric_name_ts')],
            },
        ),
    ]
