# Generated by Django 5.2.15 on 2026-08-30 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0008_monitorrule_rule_kind'),
        ('workers', '0020_worker_delete_agent_alter_devicegroup_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorevent',
            name='agent',
            field=models.ForeignKey(help_text='事件来源的 Agent 记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_events', to='workers.Worker', verbose_name='关联 Agent'),
        ),
        migrations.AlterField(
            model_name='slametric',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent that reported this metric (null for system-level metrics).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='workers.Worker', verbose_name='Agent'),
        ),
    ]
