# Generated by Django 5.2.14 on 2026-05-21 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_oauth_totp'),
        ('workers', '0003_device_devicegroup_device_idx_device_type_and_more'),
        ('resources', '0003_recognizerbenchmark_template_templateannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreflightCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('device_online', '设备在线'), ('account_valid', '账户有效'), ('resource_ready', '资源就绪'), ('agent_connected', 'Agent 连接'), ('schedule_valid', '调度规则有效')], max_length=50, verbose_name='检查类型')),
                ('target_id', models.CharField(max_length=100, verbose_name='目标 ID')),
                ('status', models.CharField(choices=[('pending', '等待检查'), ('pass', '通过'), ('fail', '失败'), ('warning', '警告')], default='pending', max_length=20, verbose_name='检查状态')),
                ('message', models.TextField(blank=True, verbose_name='检查信息')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
            ],
            options={
                'verbose_name': '预热检查记录',
                'verbose_name_plural': '预热检查记录',
                'db_table': 'scheduler_preflight_check',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_level', models.CharField(choices=[('step', '步骤级'), ('task', '任务级'), ('app', '应用级'), ('device', '设备级'), ('system', '系统级')], max_length=20, verbose_name='恢复级别')),
                ('trigger_event', models.CharField(max_length=100, verbose_name='触发事件')),
                ('action_taken', models.CharField(max_length=100, verbose_name='执行动作')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('details', models.JSONField(default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '恢复操作日志',
                'verbose_name_plural': '恢复操作日志',
                'db_table': 'scheduler_recovery_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAccountRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('rotation_strategy', models.CharField(choices=[('sequential', '顺序循环'), ('random', '随机'), ('by_stamina', '按体力余量'), ('by_last_executed', '最久未执行优先')], default='sequential', max_length=50, verbose_name='轮换策略')),
                ('switch_interval_seconds', models.IntegerField(default=10, verbose_name='切换间隔（秒）')),
                ('auto_skip_blocked', models.BooleanField(default=True, verbose_name='自动跳过异常账户')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('accounts', models.ManyToManyField(related_name='rotation_rules', to='accounts.gameaccount', verbose_name='关联账户')),
            ],
            options={
                'verbose_name': '游戏账户轮换规则',
                'verbose_name_plural': '游戏账户轮换规则',
                'db_table': 'scheduler_game_account_rotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceResourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认映射')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_mappings', to='workers.Worker', verbose_name='设备/Agent')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcepack', verbose_name='资源包')),
            ],
            options={
                'verbose_name': '设备资源包映射',
                'verbose_name_plural': '设备资源包映射',
                'db_table': 'scheduler_device_resource_mapping',
                'ordering': ['-created_at'],
                'unique_together': {('device', 'resource_pack')},
            },
        ),
    ]
