# Generated by Django 5.2.14 on 2026-05-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_phase4_accounts'),
        ('tasks', '0013_task_preflight_config_task_recovery_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceresourcemapping',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='tasks.task', verbose_name='关联任务'),
        ),
    ]
