# Generated by Django 5.2.14 on 2026-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_phase5_bindings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoStopCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('consecutive_failures', '连续失败 N 次'), ('device_offline', '设备离线超过 N 分钟'), ('all_completed', '所有账户均已执行完毕'), ('window_end', '时间窗口结束'), ('manual_stop', '手动停止'), ('resource_insufficient', '资源包不足')], max_length=50, unique=True, verbose_name='条件类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('threshold', models.IntegerField(blank=True, help_text='连续失败次数、离线分钟数等', null=True, verbose_name='阈值')),
                ('action', models.CharField(choices=[('stop_all', '停止所有'), ('stop_device', '仅停止该设备'), ('notify_continue', '发送通知并继续')], default='stop_all', max_length=20, verbose_name='触发动作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自动停止条件',
                'verbose_name_plural': '自动停止条件',
                'db_table': 'scheduler_auto_stop_condition',
                'ordering': ['condition_type'],
            },
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='窗口开始时间')),
                ('end_time', models.TimeField(verbose_name='窗口结束时间')),
                ('days_of_week', models.JSONField(default=list, help_text='星期几列表，0=周日 6=周六，空数组表示每天', verbose_name='适用星期')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '时间窗口',
                'verbose_name_plural': '时间窗口',
                'db_table': 'scheduler_time_window',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WarmupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.JSONField(default=list, verbose_name='预热步骤列表')),
                ('global_timeout_seconds', models.IntegerField(default=600, verbose_name='全局超时（秒）')),
                ('failure_strategy', models.CharField(choices=[('skip_device', '跳过该设备'), ('retry_then_skip', '重试后跳过'), ('abort_all', '中止全部')], default='skip_device', max_length=20, verbose_name='失败策略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备预热配置',
                'verbose_name_plural': '设备预热配置',
                'db_table': 'scheduler_warmup_config',
            },
        ),
    ]
