# Generated by Django 5.2.14 on 2026-05-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_add_agent_health_fields'),
        ('scheduler', '0004_phase6_unattended_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceresourcemapping',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_mappings', to='workers.Device', verbose_name='设备'),
        ),
    ]
