# Generated by Django 5.2.14 on 2026-05-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_deviceresourcemapping_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceResourceMapping',
        ),
    ]
