# Generated by Django 5.2.15 on 2026-07-14 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_delete_deviceresourcemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnattendedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('init', '初始化'), ('running', '运行中'), ('paused', '已暂停'), ('stopping', '停止中'), ('stopped', '已停止'), ('failed', '异常终止')], default='init', max_length=20, verbose_name='会话状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='停止时间')),
                ('stop_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='停止原因')),
                ('total_devices', models.IntegerField(default=0, verbose_name='设备总数')),
                ('total_accounts', models.IntegerField(default=0, verbose_name='派发账户数')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='暂停时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unattended_sessions', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
            ],
            options={
                'verbose_name': '无人值守会话',
                'verbose_name_plural': '无人值守会话',
                'db_table': 'scheduler_unattended_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
