# Generated by Django 5.2.15 on 2026-07-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_task_chain_execution_device_fk_game_account'),
        ('scheduler', '0007_unattended_session_p009'),
    ]

    operations = [
        migrations.AddField(
            model_name='unattendedsession',
            name='active_chain_executions',
            field=models.ManyToManyField(blank=True, related_name='unattended_sessions', to='pipeline.taskchainexecution', verbose_name='活跃任务链执行'),
        ),
        migrations.AddField(
            model_name='unattendedsession',
            name='dispatched_account_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='已派发账户 ID 列表'),
        ),
        migrations.AddField(
            model_name='unattendedsession',
            name='rotation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduler.gameaccountrotation', verbose_name='轮换规则'),
        ),
    ]
