# Generated by Django 5.2.15 on 2026-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_unattended_session_p009_phase2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unattendedsession',
            name='completed_chain_count',
            field=models.IntegerField(default=0, verbose_name='已完成任务链数'),
        ),
        migrations.AddField(
            model_name='unattendedsession',
            name='failed_count',
            field=models.IntegerField(default=0, verbose_name='连续失败计数'),
        ),
    ]
