# Generated by Django 5.2.15 on 2026-07-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0007_gameprofile_routine_path'),
        ('scheduler', '0009_unattended_session_p009_phase3_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unattendedsession',
            name='game_profile',
            field=models.ForeignKey(blank=True, help_text='P-011: 多 session 并行分组边界，按游戏档案隔离', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unattended_sessions', to='gamestate.gameprofile', verbose_name='关联游戏档案'),
        ),
    ]
