# Generated by Django 5.2.15 on 2026-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_scheduler_textchoices_owner_set_null_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='unattendedsession',
            name='loop_rotation',
            field=models.BooleanField(default=False, help_text='完成一轮后归还账户继续派发，配合轮换规则使用；循环模式不触发 all_completed 自动停止', verbose_name='循环轮换'),
        ),
    ]
