# Generated by Django 5.2.15 on 2026-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_base_loop_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='unattendedsession',
            name='rotation_index',
            field=models.IntegerField(default=0, help_text='loop_rotation 模式下的公平轮换游标：每次派发后自增，保证多账户轮流而非总选队首', verbose_name='轮换游标'),
        ),
    ]
