/**
 * Re-export generated OpenAPI types under a stable namespace.
 *
 * Import from this file instead of `api.generated.ts` so that the project
 * can switch generators or adjust naming without touching every consumer.
 *
 * Generated by `npm run generate:api-types`.
 */
export type * as API from './api.generated';
