# Generated by Django 5.2.14 on 2026-05-16 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('task_definition', models.JSONField(default=dict, verbose_name='任务定义')),
                ('params_config', models.JSONField(blank=True, default=dict, verbose_name='参数配置')),
                ('json_schema', models.JSONField(blank=True, default=dict, verbose_name='JSON Schema')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tasks', to='resources.resourcepack', verbose_name='资源包')),
            ],
            options={
                'verbose_name': '自定义任务',
                'verbose_name_plural': '自定义任务',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('execution_mode', models.CharField(choices=[('chain', 'Chain'), ('state_machine', 'State Machine')], default='chain', max_length=20, verbose_name='执行模式')),
                ('task_definition', models.JSONField(default=dict, verbose_name='任务定义')),
                ('params_config', models.JSONField(blank=True, default=dict, verbose_name='参数配置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='resources.resourcepack', verbose_name='资源包')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-id'],
                'unique_together': {('name', 'resource_pack')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('one_time', 'One Time'), ('periodic', 'Periodic')], max_length=20, verbose_name='调度类型')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Cron 表达式')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='计划执行时间')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('custom_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.customtask', verbose_name='关联自定义任务')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='resources.resourcepack', verbose_name='资源包')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('force_terminated', 'Force Terminated')], default='pending', max_length=20, verbose_name='执行状态')),
                ('log', models.TextField(blank=True, verbose_name='执行日志')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='取消原因')),
                ('screenshot_path', models.CharField(blank=True, max_length=512, verbose_name='截图路径')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='执行耗时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agents.agent', verbose_name='执行 Agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task', verbose_name='关联任务')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
            ],
            options={
                'verbose_name': '任务执行记录',
                'verbose_name_plural': '任务执行记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(verbose_name='步骤序号')),
                ('step_name', models.CharField(max_length=255, verbose_name='步骤名称')),
                ('step_type', models.CharField(max_length=50, verbose_name='步骤类型')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='步骤状态')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('screenshot_path', models.CharField(blank=True, max_length=512, verbose_name='截图路径')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='步骤耗时')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.taskexecution', verbose_name='关联执行记录')),
            ],
            options={
                'verbose_name': '任务步骤',
                'verbose_name_plural': '任务步骤',
                'ordering': ['step_index'],
            },
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task', 'status'], name='idx_taskexec_task_status'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['agent', 'status'], name='idx_taskexec_agent_status'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['created_at'], name='idx_taskexec_created'),
        ),
        migrations.AlterUniqueTogether(
            name='taskstep',
            unique_together={('execution', 'step_index')},
        ),
    ]
