# Generated by Django 5.2.14 on 2026-05-16 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_scheduledtask_table_alter_taskstep_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=255, unique=True, verbose_name='配置键')),
                ('setting_value', models.JSONField(default=dict, verbose_name='配置值')),
                ('category', models.CharField(default='general', max_length=100, verbose_name='配置分类')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='配置说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '应用设置',
                'verbose_name_plural': '应用设置',
                'db_table': 'tasks_appsettings',
                'ordering': ['category', 'setting_key'],
            },
        ),
    ]
