# Generated by Django 5.2.14 on 2026-05-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_recognizerbenchmark_template_templateannotation'),
        ('tasks', '0003_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(verbose_name='步骤序号')),
                ('step_type', models.CharField(max_length=50, verbose_name='步骤类型')),
                ('step_name', models.CharField(max_length=255, verbose_name='步骤名称')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='步骤状态')),
                ('screenshot_path', models.CharField(blank=True, max_length=512, verbose_name='截图路径')),
                ('recognition_result', models.JSONField(blank=True, default=dict, verbose_name='识别结果')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('trace_id', models.UUIDField(blank=True, null=True, verbose_name='追踪ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('task_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_steps', to='tasks.taskexecution', verbose_name='关联执行记录')),
            ],
            options={
                'verbose_name': '执行步骤',
                'verbose_name_plural': '执行步骤',
                'db_table': 'tasks_executionstep',
                'ordering': ['step_index'],
                'unique_together': {('task_result', 'step_index')},
            },
        ),
        migrations.CreateModel(
            name='TaskChainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField(blank=True, default=dict, verbose_name='条件配置')),
                ('order', models.IntegerField(verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.taskchainnode', verbose_name='父节点')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_nodes', to='tasks.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务链节点',
                'verbose_name_plural': '任务链节点',
                'db_table': 'tasks_taskchainnode',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEffectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='总尝试次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最后成功时间')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('is_suspected_invalid', models.BooleanField(default=False, verbose_name='疑似无效')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_records', to='resources.template', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '模板有效性',
                'verbose_name_plural': '模板有效性',
                'db_table': 'tasks_templateeffectiveness',
            },
        ),
        migrations.CreateModel(
            name='ScreenshotFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.IntegerField(verbose_name='帧序号')),
                ('image_path', models.CharField(max_length=512, verbose_name='图片路径')),
                ('timestamp_ms', models.IntegerField(verbose_name='时间戳(ms)')),
                ('overlay_data', models.JSONField(blank=True, default=dict, verbose_name='叠加数据')),
                ('execution_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_frames', to='tasks.executionstep', verbose_name='关联执行步骤')),
            ],
            options={
                'verbose_name': '截图帧',
                'verbose_name_plural': '截图帧',
                'db_table': 'tasks_screenshotframe',
                'ordering': ['frame_index'],
                'unique_together': {('execution_step', 'frame_index')},
            },
        ),
    ]
