# Generated by Django 5.2.14 on 2026-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
