# Generated by Django 5.2.14 on 2026-05-19 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_game_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('pipeline_data', models.JSONField(default=dict, verbose_name='Pipeline JSON 数据')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipeline',
                'db_table': 'pipeline',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_data', models.JSONField(verbose_name='快照数据')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tasks.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline 快照',
                'verbose_name_plural': 'Pipeline 快照',
                'db_table': 'pipeline_snapshot',
                'ordering': ['-version'],
            },
        ),
    ]
