# Generated by Django 5.2.14 on 2026-05-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_pipeline_pipelinesnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstep',
            name='duration',
            field=models.FloatField(default=0, verbose_name='耗时(秒)'),
        ),
        migrations.AddField(
            model_name='executionstep',
            name='node_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='节点ID'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='最近错误信息'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='暂停时间'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='recovery_attempts',
            field=models.IntegerField(default=0, verbose_name='恢复尝试次数'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='recovery_layer',
            field=models.IntegerField(default=0, verbose_name='当前恢复层级'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='恢复时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('force_terminated', 'Force Terminated')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
        migrations.CreateModel(
            name='RecoveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_1_retry_count', models.IntegerField(default=3, verbose_name='步骤重试次数')),
                ('layer_1_retry_interval', models.IntegerField(default=1000, verbose_name='重试间隔(ms)')),
                ('layer_2_max_consecutive_fails', models.IntegerField(default=5, verbose_name='连续失败任务重启阈值')),
                ('layer_3_app_restart_enabled', models.BooleanField(default=True, verbose_name='应用重启')),
                ('layer_4_device_reconnect_enabled', models.BooleanField(default=True, verbose_name='设备重连')),
                ('layer_5_alert_enabled', models.BooleanField(default=True, verbose_name='系统告警')),
                ('execution_timeout', models.IntegerField(default=3600, verbose_name='执行超时(秒)')),
                ('step_timeout', models.IntegerField(default=300, verbose_name='步骤超时(秒)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '恢复策略配置',
                'verbose_name_plural': '恢复策略配置',
                'db_table': 'recovery_config',
            },
        ),
    ]
