# Generated by Django 5.2.14 on 2026-05-19 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_executionstep_duration_executionstep_node_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签列表'),
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='通用', max_length=100, verbose_name='游戏名称')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('screenshot_urls', models.JSONField(default=list, verbose_name='截图URL列表')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已发布'), ('rejected', '已拒绝'), ('removed', '已下架')], default='pending', max_length=20, verbose_name='状态')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('rating_avg', models.FloatField(default=0, verbose_name='平均评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评分人数')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='tasks.pipeline', verbose_name='关联Pipeline')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_items', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '市场条目',
                'verbose_name_plural': '市场条目',
                'db_table': 'marketplace_item',
                'ordering': ['-download_count', '-rating_avg'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('recording_data', models.JSONField(default=dict, verbose_name='录制数据JSON')),
                ('pipeline_json', models.JSONField(blank=True, default=dict, verbose_name='转换后的Pipeline JSON')),
                ('duration', models.FloatField(default=0, verbose_name='录制时长(秒)')),
                ('screenshot_count', models.IntegerField(default=0, verbose_name='截图数量')),
                ('resolution', models.CharField(default='1920x1080', max_length=50, verbose_name='分辨率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '录制',
                'verbose_name_plural': '录制',
                'db_table': 'recording',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='评分(1-5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.marketplaceitem', verbose_name='市场条目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '市场评价',
                'verbose_name_plural': '市场评价',
                'db_table': 'marketplace_review',
                'unique_together': {('item', 'user')},
            },
        ),
    ]
