# Generated by Django 5.2.14 on 2026-05-19 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_device_devicegroup_device_idx_device_type_and_more'),
        ('tasks', '0008_task_tags_marketplaceitem_recording_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(max_length=50, verbose_name='规则类型')),
                ('threshold', models.IntegerField(default=3, verbose_name='阈值')),
                ('enabled', models.BooleanField(default=True, verbose_name='已启用')),
                ('quiet_start', models.TimeField(null=True, verbose_name='静默开始')),
                ('quiet_end', models.TimeField(null=True, verbose_name='静默结束')),
                ('notify_methods', models.JSONField(default=list, verbose_name='通知方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alert_rule',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('system', '系统'), ('alert', '告警'), ('community', '社区'), ('other', '其他')], default='system', max_length=20, verbose_name='分类')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_url', models.CharField(blank=True, default='', max_length=500, verbose_name='关联链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('metric_value', models.FloatField(verbose_name='指标值')),
                ('tags', models.JSONField(default=dict, verbose_name='标签')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='workers.Worker', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'SLA 指标',
                'verbose_name_plural': 'SLA 指标',
                'db_table': 'sla_metric',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('channel', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('dingtalk', '钉钉'), ('wecom', '企业微信')], max_length=20, verbose_name='渠道')),
                ('webhook_url', models.CharField(max_length=500, verbose_name='Webhook URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='已启用')),
                ('last_test_at', models.DateTimeField(null=True, verbose_name='最近测试时间')),
                ('last_test_result', models.BooleanField(default=False, verbose_name='测试结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_webhooks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhook',
                'db_table': 'webhook',
            },
        ),
    ]
