# Generated by Django 5.2.14 on 2026-05-19 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alertrule_notification_slametric_webhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='服务名')),
                ('error_type', models.CharField(max_length=255, verbose_name='错误类型')),
                ('error_message', models.TextField(verbose_name='错误信息')),
                ('stack_trace', models.TextField(blank=True, default='', verbose_name='堆栈跟踪')),
                ('platform', models.CharField(blank=True, default='', max_length=50, verbose_name='平台')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本')),
                ('resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '崩溃报告',
                'verbose_name_plural': '崩溃报告',
                'db_table': 'crash_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='templateeffectiveness',
            name='avg_confidence',
            field=models.FloatField(default=0, verbose_name='平均置信度'),
        ),
        migrations.AddField(
            model_name='templateeffectiveness',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='templateeffectiveness',
            name='fail_count',
            field=models.IntegerField(default=0, verbose_name='失败次数'),
        ),
        migrations.AddField(
            model_name='templateeffectiveness',
            name='last_match_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后匹配时间'),
        ),
        migrations.AddField(
            model_name='templateeffectiveness',
            name='template_name',
            field=models.CharField(default='', max_length=255, verbose_name='模板名称'),
        ),
        migrations.AddField(
            model_name='templateeffectiveness',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('execute', '执行'), ('import', '导入'), ('export', '导出')], max_length=20, verbose_name='操作')),
                ('resource_type', models.CharField(max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=255, verbose_name='资源ID')),
                ('details', models.JSONField(default=dict, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=64, verbose_name='Trace ID')),
                ('span_id', models.CharField(max_length=64, verbose_name='Span ID')),
                ('parent_span_id', models.CharField(blank=True, default='', max_length=64, verbose_name='父 Span ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='服务名')),
                ('operation_name', models.CharField(max_length=200, verbose_name='操作名')),
                ('status', models.CharField(default='ok', max_length=20, verbose_name='状态')),
                ('duration_ms', models.FloatField(default=0, verbose_name='耗时(ms)')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Trace Span',
                'verbose_name_plural': 'Trace Spans',
                'db_table': 'trace_span',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trace_id'], name='trace_span_trace_i_68fd64_idx'), models.Index(fields=['-created_at'], name='trace_span_created_2d7c92_idx')],
            },
        ),
    ]
