# Generated by Django 5.2.14 on 2026-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_gameprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='功能名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('rollout_percentage', models.IntegerField(default=100, verbose_name='灰度百分比 (0-100)')),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='允许的角色列表')),
                ('allowed_ips', models.JSONField(blank=True, default=list, verbose_name='允许的 IP 列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '功能开关',
                'verbose_name_plural': '功能开关',
                'db_table': 'feature_flag',
                'ordering': ['name'],
            },
        ),
    ]
