# Generated by Django 5.2.14 on 2026-05-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_featureflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='preflight_config',
            field=models.JSONField(blank=True, default=list, verbose_name='预检配置'),
        ),
        migrations.AddField(
            model_name='task',
            name='recovery_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='恢复配置'),
        ),
        migrations.AddField(
            model_name='task',
            name='retry_policy',
            field=models.JSONField(blank=True, default=dict, verbose_name='重试策略'),
        ),
    ]
