# Generated by Django 5.2.14 on 2026-05-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phase5_bindings'),
        ('scheduler', '0003_phase5_bindings'),
        ('tasks', '0013_task_preflight_config_task_recovery_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='game_accounts',
            field=models.ManyToManyField(blank=True, related_name='bound_tasks', to='accounts.gameaccount', verbose_name='游戏账户'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_concurrency',
            field=models.IntegerField(default=1, verbose_name='最大并发数'),
        ),
        migrations.AddField(
            model_name='task',
            name='parallel_mode',
            field=models.BooleanField(default=False, verbose_name='并行模式'),
        ),
        migrations.AddField(
            model_name='task',
            name='rotation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_tasks', to='scheduler.gameaccountrotation', verbose_name='轮换规则'),
        ),
        migrations.CreateModel(
            name='TaskFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件夹名称')),
                ('slug', models.SlugField(max_length=200, verbose_name='文件夹标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_folders', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.taskfolder', verbose_name='父文件夹')),
            ],
            options={
                'verbose_name': '任务文件夹',
                'verbose_name_plural': '任务文件夹',
                'db_table': 'tasks_taskfolder',
                'ordering': ['name'],
                'unique_together': {('owner', 'slug', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskfolder', verbose_name='所属文件夹'),
        ),
    ]
