# Generated by Django 5.2.14 on 2026-05-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskexecution_updated_at'),
        ('tasks', '0014_phase5_bindings'),
    ]

    operations = [
    ]
