# Generated by Django 5.2.14 on 2026-05-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_recognizerbenchmark_template_templateannotation'),
        ('tasks', '0015_merge_20260523_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resource_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='resources.resourcepack', verbose_name='资源包'),
        ),
    ]
