# Generated by Django 5.2.14 on 2026-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_recognizerbenchmark_template_templateannotation'),
        ('tasks', '0016_task_resource_pack_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customtask',
            name='resource_pack',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='resource_pack',
        ),
        migrations.AddField(
            model_name='customtask',
            name='resource_packs',
            field=models.ManyToManyField(blank=True, related_name='custom_tasks', to='resources.resourcepack', verbose_name='关联资源包'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='resource_packs',
            field=models.ManyToManyField(blank=True, related_name='scheduled_tasks', to='resources.resourcepack', verbose_name='关联资源包'),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_packs',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='resources.resourcepack', verbose_name='关联资源包'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='resource_pack',
        ),
    ]
