# Generated by Django 5.2.14 on 2026-05-27 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('snapshot', models.JSONField(help_text='Complete task configuration JSON at the time of version save', verbose_name='任务配置快照')),
                ('change_description', models.TextField(blank=True, verbose_name='变更描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tasks.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务版本',
                'verbose_name_plural': '任务版本',
                'db_table': 'tasks_taskversion',
                'ordering': ['-version_number'],
                'unique_together': {('task', 'version_number')},
            },
        ),
    ]
