# Generated by Django 5.2.14 on 2026-05-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_version_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='sub_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_pipelines', to='tasks.pipeline', verbose_name='子流程引用'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='execution_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='执行快照'),
        ),
    ]
