# Generated by Django 5.2.14 on 2026-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_pipeline_sub_pipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('manual', '手动创建'), ('yaml_import', 'YAML导入')], default='manual', max_length=20, verbose_name='来源类型'),
        ),
    ]
