# Generated by Django 5.2.14 on 2026-05-29 16:37
# Enhanced with data migration: M2M → FK (take first resource_pack_id per row)

import django.db.models.deletion
from django.db import migrations, models


def migrate_m2m_to_fk_forward(apps, schema_editor):
    """Migrate M2M intermediate table data to new FK column before dropping M2M."""
    Task = apps.get_model('tasks', 'Task')
    CustomTask = apps.get_model('tasks', 'CustomTask')
    ScheduledTask = apps.get_model('tasks', 'ScheduledTask')

    for model_cls in (Task, CustomTask, ScheduledTask):
        m2m_field_name = 'resource_packs'
        if not hasattr(model_cls, m2m_field_name):
            continue
        for obj in model_cls.objects.all():
            packs = getattr(obj, m2m_field_name).all()
            if packs.exists():
                obj.resource_pack = packs.first()
                obj.save(update_fields=['resource_pack'])


def migrate_m2m_to_fk_reverse(apps, schema_editor):
    """Reverse: no-op (M2M tables will be recreated by ReverseRemoveField)."""


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_config_data'),
        ('tasks', '0020_add_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='resource_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tasks', to='resources.resourcepack', verbose_name='Associated resource pack'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='resource_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='resources.resourcepack', verbose_name='Associated resource pack'),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='resources.resourcepack', verbose_name='Associated resource pack'),
        ),
        migrations.RunPython(migrate_m2m_to_fk_forward, migrate_m2m_to_fk_reverse),
        migrations.RemoveField(
            model_name='customtask',
            name='resource_packs',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='resource_packs',
        ),
        migrations.RemoveField(
            model_name='task',
            name='resource_packs',
        ),
    ]
