# Generated by Django 5.2.14 on 2026-05-31 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_device_metadata_enhancement'),
        ('tasks', '0021_remove_customtask_resource_packs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='resource_pack',
        ),
        migrations.CreateModel(
            name='TaskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认设备')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_mappings', to='agents.device', verbose_name='关联设备')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='tasks.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务设备映射',
                'verbose_name_plural': '任务设备映射',
                'db_table': 'tasks_taskdevice',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'device')},
            },
        ),
    ]
