# Generated by Django 5.2.14 on 2026-05-31 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_task_resource_pack_taskdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务链名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('dag_data', models.JSONField(default=dict, verbose_name='DAG 图数据 (React Flow nodes + edges)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_chains', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '任务链',
                'verbose_name_plural': '任务链',
                'db_table': 'tasks_taskchain',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskchainnode',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_nodes', to='tasks.taskchain', verbose_name='关联任务链'),
        ),
    ]
