# Generated by Django 5.2.15 on 2026-06-26 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_device_metadata_enhancement'),
        ('tasks', '0023_taskchain_taskchainnode_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='quiet_end',
            field=models.TimeField(blank=True, null=True, verbose_name='静默结束'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='quiet_start',
            field=models.TimeField(blank=True, null=True, verbose_name='静默开始'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分(1-5)'),
        ),
        migrations.AlterField(
            model_name='slametric',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='workers.Worker', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_test_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近测试时间'),
        ),
    ]
