# Generated by Django 5.2.15 on 2026-07-05 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_r37_p1_game_profile_fk'),
        ('agents', '0010_r37_p1_game_profile_fk'),
        ('resources', '0007_r37_p1_game_profile_fk'),
        ('scheduler', '0006_delete_deviceresourcemapping'),
        ('tasks', '0025_pipeline_execution_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='game_profile',
            field=models.ForeignKey(blank=True, help_text='R37-P1: 任务所属的游戏档案（nullable，兼容老任务）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.gameprofile', verbose_name='所属游戏档案'),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_pack',
            field=models.ForeignKey(blank=True, help_text='R37-P1: 任务关联的资源包（nullable，撤销 0022 过度删除后重新引入）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='resources.resourcepack', verbose_name='关联资源包'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='enabled',
            field=models.BooleanField(default=True, help_text='标记规则是否启用', verbose_name='已启用'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='name',
            field=models.CharField(help_text='告警规则的名称', max_length=100, verbose_name='规则名称'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='notify_methods',
            field=models.JSONField(default=list, help_text='告警触发的通知方式列表', verbose_name='通知方式'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='quiet_end',
            field=models.TimeField(blank=True, help_text='静默时段的结束时间', null=True, verbose_name='静默结束'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='quiet_start',
            field=models.TimeField(blank=True, help_text='静默时段的开始时间', null=True, verbose_name='静默开始'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='rule_type',
            field=models.CharField(help_text='告警规则的类型标识', max_length=50, verbose_name='规则类型'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threshold',
            field=models.IntegerField(default=3, help_text='触发告警的阈值', verbose_name='阈值'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='user',
            field=models.ForeignKey(help_text='规则所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='task_alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='category',
            field=models.CharField(default='general', help_text='配置项所属分类', max_length=100, verbose_name='配置分类'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='description',
            field=models.CharField(blank=True, help_text='配置项的说明描述', max_length=512, verbose_name='配置说明'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='setting_key',
            field=models.CharField(help_text='配置项的唯一键名', max_length=255, unique=True, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='setting_value',
            field=models.JSONField(default=dict, help_text='配置项的值', verbose_name='配置值'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='最近更新该配置的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('execute', '执行'), ('import', '导入'), ('export', '导出')], help_text='操作: login/logout/create/update/delete/execute/import/export', max_length=20, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='操作发生的时间', verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, help_text='操作的详细信息', verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='操作发起的 IP 地址', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, default='', help_text='被操作资源的标识', max_length=255, verbose_name='资源ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(help_text='被操作资源的类型', max_length=100, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(help_text='执行操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='error_message',
            field=models.TextField(help_text='错误的详细信息', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='error_type',
            field=models.CharField(help_text='错误的类型标识', max_length=255, verbose_name='错误类型'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='platform',
            field=models.CharField(blank=True, default='', help_text='崩溃发生的平台', max_length=50, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='resolved',
            field=models.BooleanField(default=False, help_text='标记崩溃是否已解决', verbose_name='已解决'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='service_name',
            field=models.CharField(help_text='崩溃发生的服务名', max_length=100, verbose_name='服务名'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='stack_trace',
            field=models.TextField(blank=True, default='', help_text='崩溃的堆栈跟踪信息', verbose_name='堆栈跟踪'),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='version',
            field=models.CharField(blank=True, default='', help_text='崩溃服务的版本号', max_length=50, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='created_by',
            field=models.ForeignKey(help_text='创建该自定义任务的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='description',
            field=models.TextField(blank=True, help_text='自定义任务的详细描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='标记自定义任务是否处于启用状态', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='json_schema',
            field=models.JSONField(blank=True, default=dict, help_text='参数配置的 JSON Schema 校验规则', verbose_name='JSON Schema'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='name',
            field=models.CharField(help_text='自定义任务的显示名称', max_length=255, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='params_config',
            field=models.JSONField(blank=True, default=dict, help_text='自定义任务运行时参数配置', verbose_name='参数配置'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='resource_pack',
            field=models.ForeignKey(blank=True, help_text='关联的资源包记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tasks', to='resources.resourcepack', verbose_name='Associated resource pack'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='task_definition',
            field=models.JSONField(default=dict, help_text='自定义任务的完整定义 JSON', verbose_name='任务定义'),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='步骤执行完成的时间', null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='duration',
            field=models.FloatField(default=0, help_text='步骤执行耗时(秒)', verbose_name='耗时(秒)'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='步骤执行耗时(毫秒)', null=True, verbose_name='耗时(ms)'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='error_message',
            field=models.TextField(blank=True, help_text='步骤执行失败的错误信息', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='node_id',
            field=models.CharField(blank=True, default='', help_text='步骤对应的节点标识', max_length=255, verbose_name='节点ID'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='recognition_result',
            field=models.JSONField(blank=True, default=dict, help_text='图像识别结果数据', verbose_name='识别结果'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='screenshot_path',
            field=models.CharField(blank=True, help_text='步骤截图文件路径', max_length=512, verbose_name='截图路径'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='步骤开始执行的时间', null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='状态: pending/running/success/failed/skipped', max_length=20, verbose_name='步骤状态'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='step_index',
            field=models.IntegerField(help_text='步骤在执行中的序号', verbose_name='步骤序号'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='step_name',
            field=models.CharField(help_text='步骤的显示名称', max_length=255, verbose_name='步骤名称'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='step_type',
            field=models.CharField(help_text='步骤的类型标识', max_length=50, verbose_name='步骤类型'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='task_result',
            field=models.ForeignKey(help_text='关联的任务执行记录', on_delete=django.db.models.deletion.CASCADE, related_name='execution_steps', to='tasks.taskexecution', verbose_name='关联执行记录'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='trace_id',
            field=models.UUIDField(blank=True, help_text='分布式追踪的 Span ID', null=True, verbose_name='追踪ID'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, help_text='允许使用该功能的 IP 白名单', verbose_name='允许的 IP 列表'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='允许使用该功能的角色列表', verbose_name='允许的角色列表'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='description',
            field=models.TextField(blank=True, default='', help_text='功能开关的说明描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='enabled',
            field=models.BooleanField(default=True, help_text='标记功能是否全局启用', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(help_text='功能开关的唯一名称', max_length=255, unique=True, verbose_name='功能名称'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='rollout_percentage',
            field=models.IntegerField(default=100, help_text='灰度发布的百分比, 0-100', verbose_name='灰度百分比 (0-100)'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='game_name',
            field=models.CharField(help_text='游戏的唯一名称', max_length=255, unique=True, verbose_name='游戏名称'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='known_popups',
            field=models.JSONField(default=list, help_text='游戏中已知弹窗的模板列表', verbose_name='已知弹窗模板列表'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='ocr_language',
            field=models.CharField(default='ch', help_text='OCR 识别使用的语言代码', max_length=50, verbose_name='OCR 语言'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='resolution_strategy',
            field=models.CharField(default='scale', help_text='分辨率适配策略标识', max_length=50, verbose_name='分辨率适配策略'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='screenshot_methods',
            field=models.JSONField(default=list, help_text='按优先级排序的截图方式列表', verbose_name='推荐截图方式排序列表'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='ui_reference_resolution',
            field=models.JSONField(default=dict, help_text='UI 设计的参考分辨率', verbose_name='UI参考分辨率 {w, h}'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='description',
            field=models.TextField(help_text='市场条目的详细描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='download_count',
            field=models.IntegerField(default=0, help_text='条目被下载的次数', verbose_name='下载次数'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='game_name',
            field=models.CharField(default='通用', help_text='条目所属的游戏名称', max_length=100, verbose_name='游戏名称'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='关联的 Pipeline 记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='tasks.pipeline', verbose_name='关联Pipeline'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='publisher',
            field=models.ForeignKey(help_text='发布该市场条目的用户', on_delete=django.db.models.deletion.CASCADE, related_name='published_items', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='rating_avg',
            field=models.FloatField(default=0, help_text='条目的平均评分', verbose_name='平均评分'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='参与评分的用户数', verbose_name='评分人数'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='screenshot_urls',
            field=models.JSONField(default=list, help_text='条目展示截图的 URL 列表', verbose_name='截图URL列表'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已发布'), ('rejected', '已拒绝'), ('removed', '已下架')], default='pending', help_text='状态: pending/approved/rejected/removed', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='tags',
            field=models.JSONField(default=list, help_text='条目的标签列表', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='title',
            field=models.CharField(help_text='市场条目的标题', max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='version',
            field=models.CharField(default='1.0', help_text='条目的版本号', max_length=50, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='用户的评论内容', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='item',
            field=models.ForeignKey(help_text='关联的市场条目', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.marketplaceitem', verbose_name='市场条目'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='rating',
            field=models.IntegerField(default=5, help_text='用户给出的评分, 范围 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分(1-5)'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='user',
            field=models.ForeignKey(help_text='发表评论的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', '系统'), ('alert', '告警'), ('community', '社区'), ('other', '其他')], default='system', help_text='分类: system/alert/community/other', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(help_text='通知的正文内容', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='标记通知是否已被阅读', verbose_name='已读'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_url',
            field=models.CharField(blank=True, default='', help_text='通知关联的资源链接', max_length=500, verbose_name='关联链接'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='通知的标题', max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='通知所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Pipeline 的详细描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(help_text='Pipeline 的显示名称', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_data',
            field=models.JSONField(default=dict, help_text='Pipeline 的完整 JSON 定义', verbose_name='Pipeline JSON 数据'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='sub_pipeline',
            field=models.ForeignKey(blank=True, help_text='引用的子 Pipeline 记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_pipelines', to='tasks.pipeline', verbose_name='子流程引用'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='user',
            field=models.ForeignKey(help_text='Pipeline 所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='version',
            field=models.IntegerField(default=1, help_text='Pipeline 的版本号', verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='pipelinesnapshot',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='版本快照的备注说明', max_length=500, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='pipelinesnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pipelinesnapshot',
            name='pipeline',
            field=models.ForeignKey(help_text='关联的 Pipeline 记录', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tasks.pipeline', verbose_name='Pipeline'),
        ),
        migrations.AlterField(
            model_name='pipelinesnapshot',
            name='pipeline_data',
            field=models.JSONField(help_text='Pipeline 版本的快照 JSON 数据', verbose_name='快照数据'),
        ),
        migrations.AlterField(
            model_name='pipelinesnapshot',
            name='version',
            field=models.IntegerField(help_text='快照对应的版本号', verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.FloatField(default=0, help_text='录制的总时长(秒)', verbose_name='录制时长(秒)'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='name',
            field=models.CharField(help_text='录制的显示名称', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='pipeline_json',
            field=models.JSONField(blank=True, default=dict, help_text='录制转换后的 Pipeline JSON', verbose_name='转换后的Pipeline JSON'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_data',
            field=models.JSONField(default=dict, help_text='录制的原始数据 JSON', verbose_name='录制数据JSON'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='resolution',
            field=models.CharField(default='1920x1080', help_text='录制的屏幕分辨率', max_length=50, verbose_name='分辨率'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='screenshot_count',
            field=models.IntegerField(default=0, help_text='录制过程中截图的总数', verbose_name='截图数量'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='user',
            field=models.ForeignKey(help_text='录制所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='execution_timeout',
            field=models.IntegerField(default=3600, help_text='任务执行总超时时间(秒)', verbose_name='执行超时(秒)'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='layer_1_retry_count',
            field=models.IntegerField(default=3, help_text='L1 层级: 单步骤重试次数', verbose_name='步骤重试次数'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='layer_1_retry_interval',
            field=models.IntegerField(default=1000, help_text='L1 层级: 步骤重试间隔(毫秒)', verbose_name='重试间隔(ms)'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='layer_2_max_consecutive_fails',
            field=models.IntegerField(default=5, help_text='L2 层级: 触发任务重启的连续失败次数', verbose_name='连续失败任务重启阈值'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='layer_3_app_restart_enabled',
            field=models.BooleanField(default=True, help_text='L3 层级: 是否启用应用重启恢复', verbose_name='应用重启'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='layer_4_device_reconnect_enabled',
            field=models.BooleanField(default=True, help_text='L4 层级: 是否启用设备重连恢复', verbose_name='设备重连'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='layer_5_alert_enabled',
            field=models.BooleanField(default=True, help_text='L5 层级: 是否启用系统告警通知', verbose_name='系统告警'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='step_timeout',
            field=models.IntegerField(default=300, help_text='单步骤执行超时时间(秒)', verbose_name='步骤超时(秒)'),
        ),
        migrations.AlterField(
            model_name='recoveryconfig',
            name='user',
            field=models.ForeignKey(help_text='配置所属的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='created_by',
            field=models.ForeignKey(help_text='创建该定时任务的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='周期性调度的 Cron 表达式', max_length=100, verbose_name='Cron 表达式'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='custom_task',
            field=models.ForeignKey(blank=True, help_text='关联的自定义任务记录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.customtask', verbose_name='关联自定义任务'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='标记定时任务是否处于启用状态', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, help_text='定时任务最近一次触发执行的时间', null=True, verbose_name='上次执行时间'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='resource_pack',
            field=models.ForeignKey(blank=True, help_text='关联的资源包记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='resources.resourcepack', verbose_name='Associated resource pack'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='schedule_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('periodic', 'Periodic')], help_text='调度类型: one_time/periodic', max_length=20, verbose_name='调度类型'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='一次性任务的计划执行时间', null=True, verbose_name='计划执行时间'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task',
            field=models.ForeignKey(blank=True, help_text='关联的任务记录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.task', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='screenshotframe',
            name='execution_step',
            field=models.ForeignKey(help_text='关联的执行步骤记录', on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_frames', to='tasks.executionstep', verbose_name='关联执行步骤'),
        ),
        migrations.AlterField(
            model_name='screenshotframe',
            name='frame_index',
            field=models.IntegerField(help_text='帧在步骤中的序号', verbose_name='帧序号'),
        ),
        migrations.AlterField(
            model_name='screenshotframe',
            name='image_path',
            field=models.CharField(help_text='截图帧图片文件路径', max_length=512, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='screenshotframe',
            name='overlay_data',
            field=models.JSONField(blank=True, default=dict, help_text='帧上叠加的标注数据', verbose_name='叠加数据'),
        ),
        migrations.AlterField(
            model_name='screenshotframe',
            name='timestamp_ms',
            field=models.IntegerField(help_text='帧采集的相对时间戳(毫秒)', verbose_name='时间戳(ms)'),
        ),
        migrations.AlterField(
            model_name='slametric',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='指标关联的 Agent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='slametric',
            name='metric_name',
            field=models.CharField(help_text='SLA 指标的名称', max_length=100, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='slametric',
            name='metric_value',
            field=models.FloatField(help_text='SLA 指标的数值', verbose_name='指标值'),
        ),
        migrations.AlterField(
            model_name='slametric',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='指标记录的时间戳', verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='slametric',
            name='tags',
            field=models.JSONField(default=dict, help_text='指标的标签字典', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='任务的详细描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='execution_mode',
            field=models.CharField(choices=[('chain', 'Chain'), ('state_machine', 'State Machine')], default='chain', help_text='执行模式: chain/state_machine', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='任务所属的文件夹', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskfolder', verbose_name='所属文件夹'),
        ),
        migrations.AlterField(
            model_name='task',
            name='game_account',
            field=models.ForeignKey(blank=True, help_text='任务关联的游戏账户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.gameaccount', verbose_name='关联游戏账户'),
        ),
        migrations.AlterField(
            model_name='task',
            name='game_accounts',
            field=models.ManyToManyField(blank=True, help_text='任务绑定的多个游戏账户', related_name='bound_tasks', to='accounts.gameaccount', verbose_name='游戏账户'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='标记任务是否处于启用状态', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_concurrency',
            field=models.IntegerField(default=1, help_text='任务允许的最大并发执行数', verbose_name='最大并发数'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='任务的显示名称', max_length=255, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parallel_mode',
            field=models.BooleanField(default=False, help_text='是否启用并行执行模式', verbose_name='并行模式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='params_config',
            field=models.JSONField(blank=True, default=dict, help_text='任务运行时参数配置', verbose_name='参数配置'),
        ),
        migrations.AlterField(
            model_name='task',
            name='preflight_config',
            field=models.JSONField(blank=True, default=list, help_text='任务执行前的预检项配置', verbose_name='预检配置'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recovery_config',
            field=models.JSONField(blank=True, default=dict, help_text='任务异常时的恢复策略配置', verbose_name='恢复配置'),
        ),
        migrations.AlterField(
            model_name='task',
            name='retry_policy',
            field=models.JSONField(blank=True, default=dict, help_text='任务失败时的重试策略配置', verbose_name='重试策略'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rotation_rule',
            field=models.ForeignKey(blank=True, help_text='关联的游戏账户轮换规则', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_tasks', to='scheduler.gameaccountrotation', verbose_name='轮换规则'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('manual', '手动创建'), ('yaml_import', 'YAML导入')], default='manual', help_text='来源: manual/yaml_import', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='任务的标签列表', verbose_name='标签列表'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_definition',
            field=models.JSONField(default=dict, help_text='任务的完整定义 JSON', verbose_name='任务定义'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='created_by',
            field=models.ForeignKey(help_text='创建该任务链的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_chains', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='dag_data',
            field=models.JSONField(default=dict, help_text='任务链的 DAG 节点和边数据', verbose_name='DAG 图数据 (React Flow nodes + edges)'),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='description',
            field=models.TextField(blank=True, default='', help_text='任务链的详细描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='标记任务链是否处于启用状态', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='name',
            field=models.CharField(help_text='任务链的显示名称', max_length=255, verbose_name='任务链名称'),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskchainnode',
            name='chain',
            field=models.ForeignKey(blank=True, help_text='节点所属的任务链', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_nodes', to='tasks.taskchain', verbose_name='关联任务链'),
        ),
        migrations.AlterField(
            model_name='taskchainnode',
            name='condition',
            field=models.JSONField(blank=True, default=dict, help_text='节点执行的条件配置', verbose_name='条件配置'),
        ),
        migrations.AlterField(
            model_name='taskchainnode',
            name='order',
            field=models.IntegerField(help_text='节点在链中的执行顺序', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='taskchainnode',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父节点, 用于构建 DAG 结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.taskchainnode', verbose_name='父节点'),
        ),
        migrations.AlterField(
            model_name='taskchainnode',
            name='task',
            field=models.ForeignKey(help_text='节点关联的任务记录', on_delete=django.db.models.deletion.CASCADE, related_name='chain_nodes', to='tasks.task', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='device',
            field=models.ForeignKey(help_text='关联的设备记录', on_delete=django.db.models.deletion.CASCADE, related_name='task_mappings', to='agents.device', verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='is_default',
            field=models.BooleanField(default=False, help_text='标记是否为任务的默认执行设备', verbose_name='是否为默认设备'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='task',
            field=models.ForeignKey(help_text='关联的任务记录', on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='tasks.task', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='agent',
            field=models.ForeignKey(help_text='执行该任务的 Agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agents.agent', verbose_name='执行 Agent'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='cancel_reason',
            field=models.CharField(blank=True, help_text='任务被取消的原因说明', max_length=255, verbose_name='取消原因'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='任务执行完成的时间', null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='duration',
            field=models.DurationField(blank=True, help_text='任务执行的总耗时', null=True, verbose_name='执行耗时'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='error_message',
            field=models.TextField(blank=True, help_text='任务执行失败的错误信息', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='execution_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='执行时的配置和环境快照', verbose_name='执行快照'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='last_error',
            field=models.TextField(blank=True, default='', help_text='最近一次错误的详细信息', verbose_name='最近错误信息'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='log',
            field=models.TextField(blank=True, help_text='任务执行的完整日志', verbose_name='执行日志'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='任务被暂停的时间', null=True, verbose_name='暂停时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='recovery_attempts',
            field=models.IntegerField(default=0, help_text='当前层级的恢复尝试次数', verbose_name='恢复尝试次数'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='recovery_layer',
            field=models.IntegerField(default=0, help_text='当前所处的恢复策略层级', verbose_name='当前恢复层级'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='result_data',
            field=models.JSONField(blank=True, default=dict, help_text='任务执行的结果数据', verbose_name='结果数据'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='resumed_at',
            field=models.DateTimeField(blank=True, help_text='任务从暂停恢复的时间', null=True, verbose_name='恢复时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='screenshot_path',
            field=models.CharField(blank=True, help_text='执行时的截图文件路径', max_length=512, verbose_name='截图路径'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='任务实际开始执行的时间', null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('force_terminated', 'Force Terminated')], default='pending', help_text='状态: pending/running/paused/success/failed/cancelled/force_terminated', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='triggered_by',
            field=models.ForeignKey(help_text='触发该次执行的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL, verbose_name='触发用户'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskfolder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskfolder',
            name='name',
            field=models.CharField(help_text='文件夹的显示名称', max_length=200, verbose_name='文件夹名称'),
        ),
        migrations.AlterField(
            model_name='taskfolder',
            name='owner',
            field=models.ForeignKey(help_text='文件夹所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='task_folders', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='taskfolder',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父文件夹, 用于构建嵌套结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.taskfolder', verbose_name='父文件夹'),
        ),
        migrations.AlterField(
            model_name='taskfolder',
            name='slug',
            field=models.SlugField(help_text='文件夹的 URL 标识', max_length=200, verbose_name='文件夹标识'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='步骤执行完成的时间', null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='duration',
            field=models.DurationField(blank=True, help_text='步骤执行的总耗时', null=True, verbose_name='步骤耗时'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='error_message',
            field=models.TextField(blank=True, help_text='步骤执行失败的错误信息', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='execution',
            field=models.ForeignKey(help_text='关联的任务执行记录', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.taskexecution', verbose_name='关联执行记录'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='result_data',
            field=models.JSONField(blank=True, default=dict, help_text='步骤执行的结果数据', verbose_name='结果数据'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='步骤已重试的次数', verbose_name='重试次数'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='screenshot_path',
            field=models.CharField(blank=True, help_text='步骤截图文件路径', max_length=512, verbose_name='截图路径'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='步骤开始执行的时间', null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='状态: pending/running/success/failed/skipped', max_length=20, verbose_name='步骤状态'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='step_index',
            field=models.IntegerField(help_text='步骤在任务中的执行序号', verbose_name='步骤序号'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='step_name',
            field=models.CharField(help_text='步骤的显示名称', max_length=255, verbose_name='步骤名称'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='step_type',
            field=models.CharField(help_text='步骤的类型标识', max_length=50, verbose_name='步骤类型'),
        ),
        migrations.AlterField(
            model_name='taskversion',
            name='change_description',
            field=models.TextField(blank=True, help_text='该版本的变更说明', verbose_name='变更描述'),
        ),
        migrations.AlterField(
            model_name='taskversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskversion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建该版本的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='taskversion',
            name='task',
            field=models.ForeignKey(help_text='关联的任务记录', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tasks.task', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='taskversion',
            name='version_number',
            field=models.IntegerField(help_text='任务的版本序号', verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='avg_confidence',
            field=models.FloatField(default=0, help_text='模板匹配的平均置信度', verbose_name='平均置信度'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='consecutive_failures',
            field=models.IntegerField(default=0, help_text='模板连续匹配失败次数', verbose_name='连续失败次数'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='fail_count',
            field=models.IntegerField(default=0, help_text='模板匹配失败次数', verbose_name='失败次数'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='is_suspected_invalid',
            field=models.BooleanField(default=False, help_text='标记模板是否疑似失效', verbose_name='疑似无效'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='last_match_time',
            field=models.DateTimeField(blank=True, help_text='模板最近一次被使用的时间', null=True, verbose_name='最后匹配时间'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='last_success_at',
            field=models.DateTimeField(blank=True, help_text='模板最近一次匹配成功的时间', null=True, verbose_name='最后成功时间'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='success_count',
            field=models.IntegerField(default=0, help_text='模板匹配成功次数', verbose_name='成功次数'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='template',
            field=models.ForeignKey(help_text='关联的模板记录', on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_records', to='resources.template', verbose_name='关联模板'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='template_name',
            field=models.CharField(default='', help_text='模板的显示名称', max_length=255, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='total_attempts',
            field=models.IntegerField(default=0, help_text='模板累计匹配尝试次数', verbose_name='总尝试次数'),
        ),
        migrations.AlterField(
            model_name='templateeffectiveness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='duration_ms',
            field=models.FloatField(default=0, help_text='Span 执行耗时(毫秒)', verbose_name='耗时(ms)'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Span 的扩展元数据', verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='operation_name',
            field=models.CharField(help_text='Span 对应的操作名称', max_length=200, verbose_name='操作名'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='parent_span_id',
            field=models.CharField(blank=True, default='', help_text='父级 Span 的 ID', max_length=64, verbose_name='父 Span ID'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='service_name',
            field=models.CharField(help_text='产生 Span 的服务名', max_length=100, verbose_name='服务名'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='span_id',
            field=models.CharField(help_text='当前 Span 的唯一 ID', max_length=64, verbose_name='Span ID'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='status',
            field=models.CharField(default='ok', help_text='Span 的执行状态', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tracespan',
            name='trace_id',
            field=models.CharField(help_text='分布式追踪的 Trace ID', max_length=64, verbose_name='Trace ID'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='channel',
            field=models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('dingtalk', '钉钉'), ('wecom', '企业微信')], help_text='渠道: discord/slack/telegram/dingtalk/wecom', max_length=20, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='enabled',
            field=models.BooleanField(default=True, help_text='标记 Webhook 是否启用', verbose_name='已启用'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_test_at',
            field=models.DateTimeField(blank=True, help_text='最近一次测试推送的时间', null=True, verbose_name='最近测试时间'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_test_result',
            field=models.BooleanField(default=False, help_text='最近一次测试推送是否成功', verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='name',
            field=models.CharField(help_text='Webhook 的显示名称', max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='user',
            field=models.ForeignKey(help_text='Webhook 所属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='task_webhooks', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='webhook_url',
            field=models.CharField(help_text='Webhook 的推送目标 URL', max_length=500, verbose_name='Webhook URL'),
        ),
    ]
