# Generated by Django 5.2.15 on 2026-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_r37_p1_game_profile_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrashReport',
        ),
    ]
