# Generated by Django 5.2.15 on 2026-07-08

"""Remove duplicate Notification + Webhook models from tasks app.

These models were duplicates of notifications.Notification and
notifications.WebhookConfig. The frontend already uses the
/api/v2/notifications/ endpoints (target app), making the tasks
versions dead code. Both tables had 0 rows in the dev DB.

TD-021 Stage 6 Task 17 (partial: Notification + Webhook group).
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_remove_duplicate_crashreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
