# Generated by Django 5.2.15 on 2026-07-08

"""Remove duplicate SLAMetric model from tasks app.

The tasks.SLAMetric model duplicated metrics.SLAMetric. As part of
TD-021 Stage 6 Task 17, the target app (metrics) was upgraded with an
`agent` FK so its schema is a strict superset of this duplicate. The
frontend has been migrated to `/api/v2/metrics/sla/`.

Both tables had 0 rows in the dev DB at migration time, so no data
backfill is required. If a production DB has rows in `sla_metric`,
they must be backfilled to `metrics_slametric` before running this
migration (field mapping: metric_value -> value, tags -> labels,
recorded_at -> timestamp; agent FK is preserved by name).
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_remove_notification_webhook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLAMetric',
        ),
    ]
