# Generated by Django 5.2.15 on 2026-07-08

"""Remove dead RecoveryConfig model from tasks app.

tasks.RecoveryConfig was a per-user recovery preferences model that
overlapped with settings.UnattendedStrategy.recovery_config (a JSONField
storing the same 5-layer recovery config as part of the global singleton).

Investigation found:
- 0 rows in the DB
- No frontend API calls to /api/v2/tasks/recovery-config/
- settings.RecoveryConfigSerializer (which serializes the JSONField
  inside UnattendedStrategy) is the ACTIVE recovery config serializer
- tasks.RecoveryConfig was the dead duplicate

TD-023 Stage 6 Task 19: deleted tasks.RecoveryConfig; kept
UnattendedStrategy (singleton) + AppSettings (key-value store) as the
two active config patterns. They serve different purposes and are NOT
duplicates — UnattendedStrategy is a typed singleton, AppSettings is a
generic key-value store.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_remove_duplicate_slametric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecoveryConfig',
        ),
    ]
