# Generated by Django 5.2.15 on 2026-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_remove_tracespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.TextField(blank=True, help_text='高层语义目标 (spec 阶段 4.3)，如"完成 BD2 日常委托"。供 LLM 诊断和任务设计文档化使用，不参与执行逻辑', verbose_name='任务目标'),
        ),
        migrations.AddField(
            model_name='task',
            name='success_criteria',
            field=models.JSONField(blank=True, default=list, help_text='任务完成的成功标准列表 (spec 阶段 4.3)，如 ["daily_missions_completed", "email_collected"]', verbose_name='成功标准'),
        ),
    ]
