# Generated by Django 5.2.15 on 2026-07-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_task_chain_executor_stage5'),
        ('tasks', '0041_task_goal_and_success_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='chain_execution',
            field=models.ForeignKey(blank=True, help_text='(spec 阶段 5) 当此执行是 TaskChain 的一部分时，指向链执行记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_executions', to='pipeline.taskchainexecution', verbose_name='关联链执行'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='chain_node',
            field=models.ForeignKey(blank=True, help_text='(spec 阶段 5) 当此执行是 TaskChain 的一部分时，指向具体的链节点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='pipeline.taskchainnode', verbose_name='关联链节点'),
        ),
    ]
