# Generated by Django 5.2.15 on 2026-07-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_task_chain_executor_stage5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='game_account',
        ),
        migrations.RemoveField(
            model_name='task',
            name='resource_pack',
        ),
    ]
