# Generated by Django 5.2.15 on 2026-07-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_window_centric_task_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdevice',
            name='is_default',
        ),
    ]
