# Generated by Django 5.2.15 on 2026-07-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_window_centric_game_account'),
        ('workers', '0013_device_game_account_fk'),
        ('tasks', '0044_task_device_remove_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Window-centric: 本次执行的具体设备（一个 task 可关联多设备，execution 记录具体在哪台执行）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executions', to='workers.Device', verbose_name='执行设备'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='game_account',
            field=models.ForeignKey(blank=True, help_text='Window-centric: 本次执行绑定的游戏账户，dispatch_task 从此读取 resource_pack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='accounts.gameaccount', verbose_name='运行时游戏账户'),
        ),
    ]
