# Generated by Django 5.2.15 on 2026-07-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_task_execution_game_account_device_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecution',
            name='last_error',
        ),
    ]
