# Generated by Django 5.2.15 on 2026-08-01 06:29

"""Add db_index=True to Task.game_profile ForeignKey for query performance.

This migration explicitly adds db_index=True to the game_profile FK field.
Although Django creates indexes on FK columns by default, this explicit
declaration makes the index intent clear at the model level and ensures
consistency across environments.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_taskexecution_trace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='game_profile',
            field=models.ForeignKey(
                blank=True,
                help_text='R37-P1: 任务所属的游戏档案（nullable，兼容老任务）',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tasks',
                to='gamestate.gameprofile',
                verbose_name='所属游戏档案',
                db_index=True,
            ),
        ),
    ]
