# Generated by Django 5.2.15 on 2026-08-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_resourcepack_game_profile_fk'),
        ('tasks', '0052_add_task_game_profile_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resource_pack',
            field=models.ForeignKey(blank=True, help_text='N197-8: 任务直接关联的资源包。任务运行时根据此资源包加载模板（图片/文字）用于识别。不同服务器可共用同一资源包，通过 ResourcePack.config_data 按 server 区分文件。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='resources.resourcepack', verbose_name='关联资源包'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, help_text='B3-3 (spec 2026-07-30-debug-directory-restructure): HTTP 请求级 trace_id (完整 UUID), 由 TracingMiddleware 注入到 ContextVar, dispatch_task 时从 current_trace_id.get() 取. 全链路贯穿: HTTP → WS 帧 → backend log → agent log → meta.json. 便于按 trace_id 反查所有相关执行记录.', max_length=64, verbose_name='Trace ID'),
        ),
    ]
