# Generated by Django 5.2.15 on 2026-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_task_resource_pack_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstep',
            name='user_message',
            field=models.TextField(blank=True, default='', help_text='由 error_code 映射的用户可读文案, 前端优先展示此字段 (N192 B1)', verbose_name='用户可读错误文案'),
        ),
    ]
