# Generated by Django 5.2.15 on 2026-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_add_executionstep_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionstep',
            name='user_message',
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='TD-351: 记录被归档的时间戳', null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='TD-351: 标记该执行为已归档状态，默认查询会过滤', verbose_name='已归档'),
        ),
    ]
