# Generated by Django 5.2.15 on 2026-08-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0055_taskexecution_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstep',
            name='user_message',
            field=models.CharField(blank=True, default='', help_text='错误码映射后的用户可读文案, 由 get_user_message() 生成', max_length=512, verbose_name='用户友好文案'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='error_code',
            field=models.CharField(blank=True, default='', help_text='任务级错误码 (DEVICE_DISCONNECTED/UNKNOWN/...), 与 agent NodeErrorCode 对齐', max_length=64, verbose_name='错误码'),
        ),
    ]
