# Generated by Django 5.2.15 on 2026-08-29 11:23
# spec 2026-08-29-game-account-game-name-retirement P7:
# MarketplaceItem.game_name 字符串 → GameProfile FK 收敛 (null = 通用)。
# 顺序: AddField(null) → 数据回填(get_or_create) → RemoveField(game_name)。

import django.db.models.deletion
from django.db import migrations, models


def backfill_game_profile(apps, schema_editor):
    """按同名 game_name get_or_create GameProfile 回填 marketplaceitem.game_profile."""
    GameProfile = apps.get_model('gamestate', 'GameProfile')
    MarketplaceItem = apps.get_model('tasks', 'MarketplaceItem')
    for item in MarketplaceItem.objects.filter(game_profile__isnull=True).only('game_name'):
        # 旧默认值 '通用' 表示无特定游戏 → 保持 null.
        if item.game_name == '通用':
            continue
        profile, _ = GameProfile.objects.get_or_create(game_name=item.game_name)
        item.game_profile = profile
        item.save(update_fields=['game_profile'])


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0010_p56_game_profile_convergence'),
        ('tasks', '0056_add_error_code_to_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='game_profile',
            field=models.ForeignKey(blank=True, help_text='条目所属的游戏档案 (Window-centric 唯一游戏维度); null = 通用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='gamestate.gameprofile', verbose_name='所属游戏档案'),
        ),
        migrations.RunPython(backfill_game_profile, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='game_name',
        ),
    ]