# Generated by Django 5.2.15 on 2026-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_p7_marketplace_game_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstep',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='步骤已重试的次数', verbose_name='重写次数'),
        ),
        migrations.DeleteModel(
            name='TaskStep',
        ),
    ]
