# Generated by Django 5.2.15 on 2026-08-30 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0058_executionstep_retry_count_delete_taskstep'),
        ('workers', '0020_worker_delete_agent_alter_devicegroup_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecution',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='执行该任务的 Agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='workers.Worker', verbose_name='执行 Agent'),
        ),
    ]
