# Generated by Django 5.2.14 on 2026-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnattendedStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_config', models.JSONField(default=dict, verbose_name='恢复策略配置')),
                ('night_mode_config', models.JSONField(default=dict, verbose_name='夜间模式配置')),
                ('frequency_limit_config', models.JSONField(default=dict, verbose_name='频率限制配置')),
                ('notification_policy', models.JSONField(default=dict, verbose_name='通知策略')),
                ('cooldown_config', models.JSONField(default=dict, verbose_name='冷却时间配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '无人值守策略配置',
                'verbose_name_plural': '无人值守策略配置',
                'db_table': 'settings_unattended_strategy',
            },
        ),
    ]
