# Generated by Django 5.2.14 on 2026-05-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_phase7_unattended_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', help_text='openai / deepseek / ollama / custom', max_length=50, verbose_name='LLM 提供商')),
                ('api_key', models.CharField(blank=True, default='', max_length=512, verbose_name='API Key')),
                ('api_base', models.CharField(blank=True, default='https://api.openai.com/v1', max_length=512, verbose_name='API Base URL')),
                ('default_model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='默认模型')),
                ('temperature', models.FloatField(default=0.3, verbose_name='温度参数')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大 Token 数')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用 LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM 配置',
                'verbose_name_plural': 'LLM 配置',
                'db_table': 'settings_llm_config',
            },
        ),
    ]
