# Generated by Django 5.2.15 on 2026-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_featureflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='api_base',
            field=models.CharField(blank=True, default='https://api.openai.com/v1', help_text='LLM 服务的 API 基础 URL', max_length=512, verbose_name='API Base URL'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='LLM 服务的 API 密钥', max_length=512, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='default_model',
            field=models.CharField(default='gpt-4o-mini', help_text='默认使用的 LLM 模型名称', max_length=100, verbose_name='默认模型'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='标记 LLM 功能是否启用', verbose_name='是否启用 LLM'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='max_tokens',
            field=models.IntegerField(default=4096, help_text='LLM 单次响应的最大 Token 数', verbose_name='最大 Token 数'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='temperature',
            field=models.FloatField(default=0.3, help_text='LLM 采样温度, 越高越随机', verbose_name='温度参数'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='cooldown_config',
            field=models.JSONField(default=dict, help_text='任务冷却时间的配置数据', verbose_name='冷却时间配置'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='frequency_limit_config',
            field=models.JSONField(default=dict, help_text='执行频率限制的配置数据', verbose_name='频率限制配置'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='标记该策略是否处于激活状态', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='night_mode_config',
            field=models.JSONField(default=dict, help_text='夜间模式的时段和限制配置', verbose_name='夜间模式配置'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='notification_policy',
            field=models.JSONField(default=dict, help_text='告警通知的策略配置', verbose_name='通知策略'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='recovery_config',
            field=models.JSONField(default=dict, help_text='5 层恢复策略的配置数据', verbose_name='恢复策略配置'),
        ),
        migrations.AlterField(
            model_name='unattendedstrategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最近一次更新的时间戳', verbose_name='更新时间'),
        ),
    ]
