# Generated by Django 5.2.15 on 2026-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_preset_multi_game_mode_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='available_models',
            field=models.JSONField(blank=True, default=list, help_text='该 provider 下可用的模型名称列表', verbose_name='模型列表'),
        ),
    ]
