# Generated by Django 5.2.15 on 2026-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_add_llm_config_available_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='input_price',
            field=models.FloatField(blank=True, help_text='每 1K tokens 的输入价格 (USD)，留空使用内置定价表', null=True, verbose_name='输入单价'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='output_price',
            field=models.FloatField(blank=True, help_text='每 1K tokens 的输出价格 (USD)，留空使用内置定价表', null=True, verbose_name='输出单价'),
        ),
    ]
