# Generated by Django 5.2.14 on 2026-05-21 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Pipeline 名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('graph_data', models.JSONField(default=dict, verbose_name='画布数据')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否为快速模板')),
                ('estimated_duration_ms', models.IntegerField(default=0, verbose_name='预估耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipeline',
                'db_table': 'pipeline_pipeline',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='快照版本号')),
                ('graph_data', models.JSONField(default=dict, verbose_name='画布数据快照')),
                ('change_summary', models.TextField(blank=True, verbose_name='变更摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pipeline.pipeline', verbose_name='关联 Pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline 版本快照',
                'verbose_name_plural': 'Pipeline 版本快照',
                'db_table': 'pipeline_version_snapshot',
                'ordering': ['-version'],
                'unique_together': {('pipeline', 'version')},
            },
        ),
    ]
