# Generated by Django 5.2.15 on 2026-07-12 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_recording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChainExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(blank=True, help_text='链执行绑定的 Agent（整条链在同一 Agent 上执行）', max_length=255, verbose_name='执行 Agent ID')),
                ('device_id', models.IntegerField(blank=True, help_text='链执行绑定的设备（整条链在同一设备上执行）', null=True, verbose_name='执行设备 ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='链执行状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, default='', help_text='链执行失败时的错误信息', verbose_name='错误信息')),
                ('chain', models.ForeignKey(help_text='执行的任务链', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pipeline.taskchain', verbose_name='关联任务链')),
                ('current_node', models.ForeignKey(blank=True, help_text='当前正在执行的 TaskChainNode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_executions', to='pipeline.taskchainnode', verbose_name='当前执行节点')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_chain_executions', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
            ],
            options={
                'verbose_name': '任务链执行记录',
                'verbose_name_plural': '任务链执行记录',
                'db_table': 'pipeline_task_chain_execution',
                'ordering': ['-started_at'],
            },
        ),
    ]
