# Generated by Django 5.2.15 on 2026-07-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0003_gameprofile'),
        ('pipeline', '0006_task_chain_executor_stage5'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchain',
            name='game_profile',
            field=models.ForeignKey(blank=True, help_text='Window-centric: 任务链归属游戏档案', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_chains', to='gamestate.gameprofile', verbose_name='所属游戏档案'),
        ),
        migrations.AddField(
            model_name='taskchain',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Window-centric: 标记为该 GameProfile 的默认任务链，一个 GameProfile 下最多一个 is_default=True', verbose_name='是否默认链'),
        ),
    ]
