# Generated by Django 5.2.15 on 2026-07-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_task_chain_execution_device_fk_game_account'),
        ('tasks', '0045_task_execution_game_account_device_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchainnode',
            name='node_type',
            field=models.CharField(choices=[('task', 'Task'), ('pipeline', 'Pipeline')], default='task', help_text='节点引用的是 Task 还是 Pipeline', max_length=10, verbose_name='节点类型'),
        ),
        migrations.AddField(
            model_name='taskchainnode',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='节点引用的 Pipeline (node_type=pipeline 时必填)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_nodes', to='pipeline.pipeline', verbose_name='关联 Pipeline'),
        ),
        migrations.AlterField(
            model_name='taskchainnode',
            name='task',
            field=models.ForeignKey(blank=True, help_text='节点关联的任务记录 (node_type=task 时必填)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_nodes', to='tasks.task', verbose_name='关联任务'),
        ),
    ]
