# Generated by Django 5.2.15 on 2026-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_taskchainnode_pipeline_fk_td110'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchainexecution',
            name='error_code',
            field=models.CharField(blank=True, default='', help_text='链级错误码 (DEVICE_DISCONNECTED/UNKNOWN/...), 与失败节点 error_code 对齐', max_length=64, verbose_name='错误码'),
        ),
    ]
