# Generated by Django 5.2.15 on 2026-06-24 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaf_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSkill',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='analysis', max_length=64)),
                ('yaml_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_custom_skill',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by', '-updated_at'], name='idx_cskill_user_updated'), models.Index(fields=['category'], name='idx_cskill_category')],
            },
        ),
    ]
