# Generated by Django 5.2.15 on 2026-07-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaf_ai', '0002_customskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('log_analysis', 'Log Analysis'), ('qa', 'Q&A')], default='log_analysis', max_length=20, verbose_name='Session type')),
                ('target_id', models.IntegerField(blank=True, help_text='Associated target ID (e.g. execution_id)', null=True, verbose_name='Target ID')),
                ('messages', models.JSONField(blank=True, default=list, help_text='LangGraph message history', verbose_name='Message history')),
                ('reasoning_steps', models.JSONField(blank=True, default=list, help_text='List of {thought, action, action_input, observation}', verbose_name='Reasoning steps')),
                ('final_summary', models.TextField(blank=True, default='', verbose_name='Final summary')),
                ('final_suggestions', models.JSONField(blank=True, default=list, verbose_name='Final suggestions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('model_used', models.CharField(blank=True, default='', max_length=100, verbose_name='Model used')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total tokens')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='Total cost')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Agent session',
                'verbose_name_plural': 'Agent sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'session_type'], name='idx_agent_session_user'), models.Index(fields=['target_id'], name='idx_agent_session_target')],
            },
        ),
    ]
