# Generated by Django 5.2.15 on 2026-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaf_ai', '0008_alter_llmusagelog_user_alter_qasession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='evidence',
            field=models.JSONField(blank=True, default=list, help_text='Evidence items backing the diagnosis (from LLM final answer)', verbose_name='Evidence'),
        ),
    ]
