# Generated by Django 5.2.15 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaf_ai', '0009_agent_session_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='evidence_check',
            field=models.JSONField(blank=True, default=None, help_text='Strong-check result: evidence items vs tool observations', null=True, verbose_name='Evidence check'),
        ),
    ]