# Generated by Django 5.2.15 on 2026-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the log record was created.', verbose_name='Timestamp')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, help_text='Log severity level.', max_length=10, verbose_name='Level')),
                ('source', models.CharField(db_index=True, help_text='Logger name (e.g. "tasks.views", "protocol.consumers").', max_length=200, verbose_name='Source')),
                ('message', models.TextField(help_text='Log message text.', verbose_name='Message')),
                ('traceback', models.TextField(blank=True, default='', help_text='Exception traceback, if the log record included exc_info.', verbose_name='Traceback')),
                ('task_id', models.IntegerField(blank=True, db_index=True, help_text='Associated task ID, if applicable.', null=True, verbose_name='Task ID')),
                ('agent_id', models.IntegerField(blank=True, db_index=True, help_text='Associated agent ID, if applicable.', null=True, verbose_name='Agent ID')),
                ('device_id', models.IntegerField(blank=True, db_index=True, help_text='Associated device ID, if applicable.', null=True, verbose_name='Device ID')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'core_log_entry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_log_en_timesta_dc477c_idx'), models.Index(fields=['level'], name='core_log_en_level_ba141e_idx'), models.Index(fields=['source'], name='core_log_en_source_f96fcf_idx')],
            },
        ),
    ]
