# Generated by Django 5.2.15 on 2026-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaf_core', '0001_initial_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, help_text='Tracing trace_id for request correlation (from TracingMiddleware contextvar)', max_length=64, null=True, verbose_name='Trace ID'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['trace_id'], name='core_log_en_trace_i_721c60_idx'),
        ),
    ]
