# Generated by Django 5.2.15 on 2026-07-11 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaf_core', '0002_add_logentry_trace_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-last_seen'], 'verbose_name': 'Log Entry', 'verbose_name_plural': 'Log Entries'},
        ),
        migrations.RemoveIndex(
            model_name='logentry',
            name='core_log_en_timesta_dc477c_idx',
        ),
        migrations.AddField(
            model_name='logentry',
            name='fingerprint',
            field=models.CharField(db_index=True, default='', help_text='SHA-256 hash of (source + level + message[:200]) for dedup. Empty for legacy rows created before this field was added.', max_length=64, verbose_name='Fingerprint'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this log was first recorded (same as timestamp for new rows).', verbose_name='First Seen'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='When this log was last seen (updated on each dedup merge).', verbose_name='Last Seen'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='occurrence_count',
            field=models.IntegerField(default=1, help_text='How many times this exact log was emitted within the dedup window.', verbose_name='Occurrence Count'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['-last_seen'], name='core_log_en_last_se_00eeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['fingerprint'], name='core_log_en_fingerp_598ed5_idx'),
        ),
    ]
