# Generated by Django 5.2.14 on 2026-05-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('game_name', models.CharField(max_length=255, verbose_name='游戏名称')),
                ('tracker_type', models.CharField(max_length=50, verbose_name='跟踪器类型')),
                ('ocr_region', models.JSONField(default=dict, verbose_name='OCR 区域')),
                ('ocr_regex', models.CharField(blank=True, max_length=500, verbose_name='OCR 正则')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='阈值')),
                ('threshold_direction', models.CharField(blank=True, max_length=10, verbose_name='阈值方向')),
                ('trigger_action', models.JSONField(default=dict, verbose_name='触发动作')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '游戏状态规则',
                'verbose_name_plural': '游戏状态规则',
                'db_table': 'gamestate_gamestaterule',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GameStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='检测值')),
                ('raw_text', models.TextField(blank=True, verbose_name='原始文本')),
                ('triggered', models.BooleanField(default=False, verbose_name='是否触发')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='gamestate.gamestaterule', verbose_name='关联规则')),
            ],
            options={
                'verbose_name': '游戏状态快照',
                'verbose_name_plural': '游戏状态快照',
                'db_table': 'gamestate_gamestatesnapshot',
                'ordering': ['-created_at'],
            },
        ),
    ]
