# Generated by Django 5.2.14 on 2026-05-21 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0001_initial'),
        ('resources', '0003_recognizerbenchmark_template_templateannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVersionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, verbose_name='游戏名称')),
                ('previous_version_hash', models.CharField(max_length=64, verbose_name='更新前版本 Hash')),
                ('current_version_hash', models.CharField(max_length=64, verbose_name='更新后版本 Hash')),
                ('files_changed', models.JSONField(default=list, verbose_name='变更文件列表')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('affected_templates', models.ManyToManyField(related_name='version_checks', to='resources.template', verbose_name='受影响模板')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcepack', verbose_name='关联资源包')),
            ],
            options={
                'verbose_name': '游戏版本更新检测',
                'verbose_name_plural': '游戏版本更新检测',
                'db_table': 'gamestate_game_version_check',
                'ordering': ['-detected_at'],
            },
        ),
    ]
