# Generated by Django 5.2.15 on 2026-07-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0003_gameprofile'),
        ('pipeline', '0007_task_chain_game_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='default_control_mode',
            field=models.CharField(blank=True, choices=[('foreground', '前台模式'), ('background', '后台模式'), ('pseudo_background', '伪后台模式')], default='', help_text='Window-centric: 前台/后台/伪后台，Device.control_mode 为空时继承', max_length=30, verbose_name='默认控制模式'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='default_input_method',
            field=models.CharField(blank=True, default='', help_text='Window-centric: 该游戏推荐的默认输入方式，Device.input_method 为空时继承', max_length=50, verbose_name='默认输入方式'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='default_routine',
            field=models.ForeignKey(blank=True, help_text='Window-centric: 日常默认任务链，新窗口绑 GameProfile 后自动继承', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_profiles', to='pipeline.taskchain', verbose_name='默认任务链'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='default_screenshot_method',
            field=models.CharField(blank=True, default='', help_text='Window-centric: 该游戏推荐的默认截图方式，Device.screenshot_method 为空时继承', max_length=50, verbose_name='默认截图方式'),
        ),
    ]
