# Generated by Django 5.2.15 on 2026-08-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0008_gameprofile_device_type_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='allowed_device_types',
            field=models.JSONField(blank=True, default=list, help_text='N197: 该游戏档案允许操作的窗口类型列表。如 ["windows", "emulator"] 表示同时支持 Windows 窗口和模拟器。空列表表示不限制（兼容所有类型）。设备绑定和任务分发时据此校验设备类型是否匹配。', verbose_name='可操作的窗口类型列表'),
        ),
    ]
