# Generated by Django 5.2.15 on 2026-08-29 11:20
# spec 2026-08-29-game-account-game-name-retirement P5+P6:
# GameStateRule / GameVersionCheck 的 game_name 字符串 → GameProfile FK 收敛。
# 顺序: AddField(null) → 数据回填(get_or_create) → RemoveField(game_name) → NOT NULL。

import django.db.models.deletion
from django.db import migrations, models


def backfill_game_profile(apps, schema_editor):
    """按同名 game_name get_or_create GameProfile 回填两个模型的 game_profile FK."""
    GameProfile = apps.get_model('gamestate', 'GameProfile')
    GameStateRule = apps.get_model('gamestate', 'GameStateRule')
    GameVersionCheck = apps.get_model('gamestate', 'GameVersionCheck')

    for model in (GameStateRule, GameVersionCheck):
        for obj in model.objects.filter(game_profile__isnull=True).only('game_name'):
            profile, _ = GameProfile.objects.get_or_create(game_name=obj.game_name)
            obj.game_profile = profile
            obj.save(update_fields=['game_profile'])


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0009_add_allowed_device_types_to_gameprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestaterule',
            name='game_profile',
            field=models.ForeignKey(help_text='规则所属的游戏档案 (Window-centric 唯一游戏维度)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_rules', to='gamestate.gameprofile', verbose_name='关联游戏档案'),
        ),
        migrations.AddField(
            model_name='gameversioncheck',
            name='game_profile',
            field=models.ForeignKey(help_text='被检测游戏 (Window-centric 唯一游戏维度)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_version_checks', to='gamestate.gameprofile', verbose_name='关联游戏档案'),
        ),
        migrations.RunPython(backfill_game_profile, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='gamestaterule',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='gameversioncheck',
            name='game_name',
        ),
        migrations.AlterField(
            model_name='gamestaterule',
            name='game_profile',
            field=models.ForeignKey(help_text='规则所属的游戏档案 (Window-centric 唯一游戏维度)', on_delete=django.db.models.deletion.PROTECT, related_name='state_rules', to='gamestate.gameprofile', verbose_name='关联游戏档案'),
        ),
        migrations.AlterField(
            model_name='gameversioncheck',
            name='game_profile',
            field=models.ForeignKey(help_text='被检测游戏 (Window-centric 唯一游戏维度)', on_delete=django.db.models.deletion.PROTECT, related_name='game_version_checks', to='gamestate.gameprofile', verbose_name='关联游戏档案'),
        ),
    ]