# Generated by Django 5.2.15 on 2026-08-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0010_p56_game_profile_convergence'),
        ('pipeline', '0010_add_error_code_to_chain_execution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprofile',
            old_name='default_routine',
            new_name='default_task_chain',
        ),
    ]
