# Generated by Django 5.2.14 on 2026-05-19 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Agent 唯一标识')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('capabilities', models.JSONField(default=dict, verbose_name='能力标签')),
                ('resource_quota', models.JSONField(default=dict, verbose_name='资源配额')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20, verbose_name='状态')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU 使用率')),
                ('memory_usage', models.FloatField(blank=True, null=True, verbose_name='内存使用率')),
                ('screenshot_fps', models.FloatField(blank=True, null=True, verbose_name='截图 FPS')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='连接时间')),
                ('disconnected_at', models.DateTimeField(blank=True, null=True, verbose_name='断开时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent 会话',
                'verbose_name_plural': 'Agent 会话',
                'db_table': 'protocol_agentsession',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MessageFrameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='追踪 ID')),
                ('message_type', models.CharField(max_length=50, verbose_name='消息类型')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10, verbose_name='消息方向')),
                ('payload', models.JSONField(default=dict, verbose_name='消息体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocol.agentsession', verbose_name='Agent 会话')),
            ],
            options={
                'verbose_name': '消息帧日志',
                'verbose_name_plural': '消息帧日志',
                'db_table': 'protocol_messageframelog',
                'ordering': ['-id'],
            },
        ),
    ]
