# Generated by Django 5.2.15 on 2026-07-20 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_agentsession_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageframelog',
            name='message_type',
            field=models.CharField(db_index=True, max_length=50, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='messageframelog',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='追踪 ID'),
        ),
    ]
