# Generated by Django 5.2.15 on 2026-08-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_td295_db_index_textfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentSession',
            new_name='WorkerSession',
        ),
        migrations.AlterModelTable(
            name='workersession',
            table='protocol_workersession',
        ),
    ]
