# Generated by Django 5.2.14 on 2026-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='资源包名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('target_app', models.CharField(blank=True, max_length=255, verbose_name='目标应用')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='作者')),
                ('directory_path', models.CharField(max_length=512, verbose_name='资源目录路径')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('gaf_version_compat', models.CharField(blank=True, max_length=100, verbose_name='GAF 版本兼容性')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源包',
                'verbose_name_plural': '资源包',
                'ordering': ['-id'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
