# Generated by Django 5.2.14 on 2026-05-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resourcepack_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizerBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognizer_type', models.CharField(max_length=50, verbose_name='识别器类型')),
                ('engine_name', models.CharField(max_length=100, verbose_name='引擎名称')),
                ('sample_count', models.IntegerField(verbose_name='样本数量')),
                ('avg_duration_ms', models.FloatField(verbose_name='平均耗时(ms)')),
                ('accuracy', models.FloatField(verbose_name='准确率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '识别器基准测试',
                'verbose_name_plural': '识别器基准测试',
                'db_table': 'resources_recognizerbenchmark',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('image_path', models.CharField(max_length=512, verbose_name='图片路径')),
                ('template_type', models.CharField(blank=True, max_length=50, verbose_name='模板类型')),
                ('match_threshold', models.FloatField(default=0.8, verbose_name='匹配阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='resources.resourcepack', verbose_name='关联资源包')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'db_table': 'resources_template',
                'ordering': ['-id'],
                'unique_together': {('resource_pack', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(max_length=50, verbose_name='标注类型')),
                ('points', models.JSONField(default=dict, verbose_name='标注坐标点')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='resources.template', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '模板标注',
                'verbose_name_plural': '模板标注',
                'db_table': 'resources_templateannotation',
                'ordering': ['-id'],
            },
        ),
    ]
