# Generated by Django 5.2.14 on 2026-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_tag_template_tags_templateversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepack',
            name='config_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Config data (settings.json content)'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='directory_path',
            field=models.CharField(max_length=512, verbose_name='Resource directory path'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='gaf_version_compat',
            field=models.CharField(blank=True, max_length=100, verbose_name='GAF version compatibility'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Resource pack name'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='target_app',
            field=models.CharField(blank=True, max_length=255, verbose_name='Target application'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Version'),
        ),
    ]
