# Generated by Django 5.2.15 on 2026-07-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_td004_single_source_of_truth'),
        ('tasks', '0025_pipeline_execution_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepack',
            name='game_profile',
            field=models.ForeignKey(blank=True, help_text='R37-P1: 资源包所属的游戏档案（nullable，兼容老资源包）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_packs', to='tasks.gameprofile', verbose_name='所属游戏档案'),
        ),
    ]
