"""check_git_status_after_hook.py — Detect MM state after hooks have run (v8.4 N105).

Background (failure mode N105, 2026-06-15):

When a pre-commit hook modifies a file that the user already staged
with `git add`, the file ends up in the `MM` state (modified in
both the index and the working tree). The pre-commit framework
re-stages the working tree after each hook, but it does NOT
automatically `git add` the hook's changes. As a result, the
`git commit` operation that the framework eventually issues sees
the staged version (not the hook's version) and rolls the file
back, while the working tree keeps the hook's version. This
manifests as the dreaded "files were modified by this hook" error.

Symptoms that this script catches:

- `MM` — staged AND work tree modified (most common; the
  classic N105 case where `gaf-sync` clobbered an auto-maintained
  file the user just regenerated).
- `MD` — staged AND work tree deleted (a hook deleted a staged
  file).
- `AM` — added in index AND work tree modified (a hook touched a
  newly-added file).
- `AD` — added in index AND work tree deleted (a hook deleted a
  newly-added file).

Exit codes:

- 0 — no hook-induced modifications; safe to commit.
- 1 — at least one file is in MM/MD/AM/AD state; commit blocked
       with a clear remediation hint.
- 2 — invocation error (not a git repo, git binary missing, etc.).

Usage:

    python check_git_status_after_hook.py            # strict, blocks on MM
    python check_git_status_after_hook.py --warn-only  # report but don't block
    python check_git_status_after_hook.py --auto-only  # only check known auto-maintained files

Hook registration (.pre-commit-config.yaml):

    - id: gaf-git-status-check
      name: GAF git status post-hook check (N105)
      entry: python scripts/hooks/check_git_status_after_hook.py
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-commit]

The hook should be declared LAST in the local hooks list so it
runs after every other hook has had a chance to (mis)modify the
working tree.
"""
from __future__ import annotations

# Bootstrap: make scripts/ importable when this file lives in a subdir.
import sys as _sys
from pathlib import Path as _Path

_SCRIPTS_DIR = _Path(__file__).resolve().parents[1]
if str(_SCRIPTS_DIR) not in _sys.path:
    _sys.path.insert(0, str(_SCRIPTS_DIR))

import argparse  # noqa: E402
import os  # noqa: E402
import shutil  # noqa: E402
import subprocess  # noqa: E402
import sys  # noqa: E402
from pathlib import Path  # noqa: E402
from typing import NamedTuple  # noqa: E402

import _encoding_safe  # noqa: E402,F401  (must be first; reconfigures stdout to UTF-8)

# Files that are *expected* to be regenerated by other sync tools
# and are therefore the most likely culprits in an N105-style
# hook-induced rollback. We treat these as the high-confidence
# "auto-maintained" set; --auto-only will restrict the scan to
# this set, --all is the default for maximum safety.
AUTO_MAINTAINED_PATHS = {
    ".ai-memory/meta/docs-index.md",
    # v9.7 (2026-07-26 TD-341): 4 个用户可读 ref 文件迁出到 docs/reference/, 不再属于 .ai-memory auto-maintained
    ".ai-memory/meta/auto-kb/api-endpoints.md",
    ".ai-memory/meta/auto-kb/agent-protocol.md",
    ".ai-memory/meta/auto-kb/pipeline-nodes.md",
    ".ai-memory/meta/auto-kb/error-codes.md",
}

# HOOK_MAINTAINED_PATHS — files that pre-commit hooks are *expected* to
# modify during their run, and therefore must NOT trigger N105 MM-state
# guard. Without this whitelist, the hook-induced write creates an
# infinite loop:
#   1. pre-commit hook writes file → working tree modified
#   2. user `git add`s the file → enters MM state
#   3. N105 hook detects MM → blocks commit
#   4. user re-runs `git add` + `git commit` → step 1 again (loop)
# Files here are skipped by scan_problems() in ALL modes (--all and
# --auto-only), since the hook write is by design.
#
# N190 (2026-07-26): added `docs/reference/performance-baseline.md` —
# governance-batch's `_append_performance_baseline()` writes a new row
# every pre-commit run (spec-2026-07-26-ai-governance-execution-rate-fix
# Wave 3), causing the MM loop. Root-cause fix (replaces --no-verify
# workaround).
HOOK_MAINTAINED_PATHS = {
    "docs/reference/performance-baseline.md",
}

# Combination of staged (X) and work-tree (Y) status codes that
# indicate a hook-induced mismatch. Index/status letters follow
# `git status --porcelain` semantics.
PROBLEMATIC_COMBOS = {
    "MM",  # staged modified + work tree modified
    "MD",  # staged modified + work tree deleted
    "AM",  # staged added    + work tree modified
    "AD",  # staged added    + work tree deleted
}


class ProblemEntry(NamedTuple):
    """One detected problem line from `git status --porcelain`."""

    status: str  # 2-char porcelain code, e.g. "MM"
    path: str  # repo-relative path


def _find_git_root(start: Path) -> Path | None:
    """Walk up from `start` looking for a directory containing `.git/`.

    Returns None if we reach the filesystem root without finding one.
    """
    start = start.resolve()
    for candidate in (start, *start.parents):
        if (candidate / ".git").exists():
            return candidate
    return None


def _git_status_porcelain(repo_root: Path) -> list[str]:
    """Return `git status --porcelain` output as a list of lines.

    Uses --porcelain=v1 (default) for stable 2-letter status codes.
    The output is read as raw bytes and decoded with `errors="replace"`
    so non-UTF-8 paths (e.g. GBK-encoded Chinese filenames on legacy
    Windows checkouts) don't crash the script.
    """
    if shutil.which("git") is None:
        print("❌ git binary not found on PATH", file=sys.stderr)
        sys.exit(2)
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=str(repo_root),
        capture_output=True,
    )
    if result.returncode != 0:
        # Decode stderr defensively in case git itself prints
        # non-UTF-8 bytes (e.g. on a localised error).
        try:
            err_text = result.stderr.decode("utf-8", errors="replace")
        except Exception:  # pragma: no cover - defensive
            err_text = "<undecodable git error>"
        print(f"❌ git status failed: {err_text.strip()}", file=sys.stderr)
        sys.exit(2)
    try:
        text = result.stdout.decode("utf-8", errors="replace")
    except Exception:  # pragma: no cover - defensive
        text = ""
    return [line for line in text.splitlines() if line]


def _parse_porcelain_line(line: str) -> ProblemEntry | None:
    """Parse one `git status --porcelain` line into a ProblemEntry.

    The first two columns are status codes; the rest is the path
    (which may contain spaces and is space-prefixed by git).
    Renamed/copied entries (RR/CC) include a ` -> ` arrow which
    we collapse to the destination path for the purpose of this
    check.
    """
    if len(line) < 3:
        return None
    status = line[:2]
    raw_path = line[3:]
    if " -> " in raw_path:
        raw_path = raw_path.split(" -> ", 1)[1]
    return ProblemEntry(status=status, path=raw_path)


def scan_problems(
    repo_root: Path,
    *,
    auto_only: bool = False,
) -> list[ProblemEntry]:
    """Return all problem entries currently present in the working tree.

    `auto_only=True` restricts the scan to files in
    `AUTO_MAINTAINED_PATHS`; this is the cheap mode that catches
    the canonical N105 case without false-positives on the
    developer's own staged+uncommitted work.

    Files in `HOOK_MAINTAINED_PATHS` are always skipped (both --all
    and --auto-only modes) — these are files that pre-commit hooks
    are expected to modify during their run, so MM state is by design
    and must not block the commit (N190 root-cause fix for the
    governance-batch ↔ N105 infinite loop).
    """
    problems: list[ProblemEntry] = []
    for line in _git_status_porcelain(repo_root):
        entry = _parse_porcelain_line(line)
        if entry is None:
            continue
        if entry.status not in PROBLEMATIC_COMBOS:
            continue
        # N190: skip files that hooks are expected to modify (e.g.
        # governance-batch writes performance-baseline.md every run).
        if entry.path in HOOK_MAINTAINED_PATHS:
            continue
        if auto_only and entry.path not in AUTO_MAINTAINED_PATHS:
            continue
        problems.append(entry)
    return problems


def format_remediation(problems: list[ProblemEntry]) -> str:
    """Produce a human-readable remediation hint for a list of problems.

    The hint covers the three most common resolutions:

    1. Stage the hook's changes: `git add <file>`
    2. Discard the hook's changes: `git checkout -- <file>`
    3. Bypass hooks entirely: `git commit --no-verify` (and accept
       that the hook's writes are lost).
    """
    lines: list[str] = []
    lines.append("N105 修复: 下列文件在 index (staged) 和 working tree 状态不一致。")
    lines.append("  这是因为某个 pre-commit hook 修改了已 staged 的文件。")
    lines.append("")
    lines.append("  决策 (3 选 1):")
    lines.append("    1. 接受 hook 改动:  git add <file>")
    lines.append("    2. 丢弃 hook 改动:  git checkout -- <file>")
    lines.append("    3. 完全绕过 hook:   git commit --no-verify -m '...'")
    lines.append("")
    lines.append("  受影响文件:")
    for p in problems:
        lines.append(f"    [{p.status}] {p.path}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Detect post-hook MM state (v8.4 N105 fix).",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Path to the git repo root (default: auto-detect from cwd).",
    )
    parser.add_argument(
        "--warn-only",
        action="store_true",
        help="Report problems but exit 0 (do not block the commit).",
    )
    parser.add_argument(
        "--auto-only",
        action="store_true",
        help="Only check known auto-maintained files (cheap mode).",
    )
    args = parser.parse_args(argv)

    if args.root:
        repo_root = Path(args.root).resolve()
    else:
        cwd = Path(os.getcwd())
        detected = _find_git_root(cwd)
        if detected is None:
            print("❌ not inside a git repository", file=sys.stderr)
            return 2
        repo_root = detected

    problems = scan_problems(repo_root, auto_only=args.auto_only)
    if not problems:
        if not args.warn_only:
            print(
                f"✅ git-status clean "
                f"({'auto-maintained only' if args.auto_only else 'all files'})"
            )
        return 0

    print(format_remediation(problems), file=sys.stderr)
    if args.warn_only:
        return 0
    return 1


if __name__ == "__main__":
    sys.exit(main())
