# Generated by Django 5.2.14 on 2026-05-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(max_length=100, verbose_name='插件名称')),
                ('event_type', models.CharField(max_length=50, verbose_name='事件类型')),
                ('hook_function', models.CharField(max_length=255, verbose_name='钩子函数')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '插件钩子',
                'verbose_name_plural': '插件钩子',
                'db_table': 'plugins_pluginhook',
                'ordering': ['-priority'],
                'unique_together': {('plugin_name', 'event_type', 'hook_function')},
            },
        ),
    ]
